"""
Script biên soạn từ điển giáo trình tiếng Lào (lao_vi_en.csv) >= 500 entries.
Bao gồm từ vựng 12 bài học giáo trình giao tiếp cơ bản:
  - lao: Từ tiếng Lào (chuẩn hóa NFC)
  - vi: Nghĩa tiếng Việt
  - en: Nghĩa tiếng Anh
  - romanization: Phiên âm Latinh
  - pos: Từ loại (noun, verb, adjective, pronoun, number, particle, phrase, adverb, conjunction)
  - lesson: Bài học (Lesson 01 - 12)
  - example_lao: Ví dụ câu tiếng Lào
  - example_vi: Nghĩa tiếng Việt của câu ví dụ
"""
import os
import sys
import csv

PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
if PROJECT_ROOT not in sys.path:
    sys.path.insert(0, PROJECT_ROOT)

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")

from src.preprocessing.normalize import normalize_lao

DICT_OUTPUT = os.path.join(PROJECT_ROOT, "data", "dictionaries", "lao_vi_en.csv")

# Danh sách từ vựng nền tảng phân theo 12 chủ đề giáo trình
VOCAB_DATABASE = [
    # =========================================================================
    # BÀI 1: CHÀO HỎI & LÀM QUEN (GREETINGS & INTRODUCTIONS) - 45 entries
    # =========================================================================
    ("ສະບາຍດີ", "Xin chào", "Hello / Good day", "sa-bai-dee", "phrase", "Bài 01", "ສະບາຍດີຕອນເຊົ້າ", "Chào buổi sáng"),
    ("ຂອບໃຈ", "Cảm ơn", "Thank you", "khop-chai", "phrase", "Bài 01", "ຂອບໃຈຫຼາຍໆ", "Cảm ơn nhiều"),
    ("ຂອບໃຈຫຼາຍໆ", "Cảm ơn rất nhiều", "Thank you very much", "khop-chai-lai-lai", "phrase", "Bài 01", "ຂອບໃຈຫຼາຍໆເດີ", "Cảm ơn nhiều nhé"),
    ("ຂໍໂທດ", "Xin lỗi", "Excuse me / Sorry", "kho-thot", "phrase", "Bài 01", "ຂໍໂທດຫຼາຍໆ", "Rất xin lỗi"),
    ("ບໍ່ເປັນຫຍັງ", "Không có chi / Không sao", "You're welcome / No problem", "baw-pen-nyang", "phrase", "Bài 01", "ບໍ່ເປັນຫຍັງດອກ", "Không sao đâu mà"),
    ("ສະບາຍດີບໍ", "Bạn có khỏe không?", "How are you?", "sa-bai-dee-baw", "phrase", "Bài 01", "ເຈົ້າສະບາຍດີບໍ", "Bạn khỏe không"),
    ("ສະບາຍດີ", "Tôi khỏe", "I'm fine", "sa-bai-dee", "phrase", "Bài 01", "ຂ້ອຍສະບາຍດີ", "Tôi khỏe mạnh"),
    ("ຍິນດີທີ່ໄດ້ຮູ້ຈັກ", "Rất vui được biết bạn", "Nice to meet you", "yin-dee-thee-dai-hu-chak", "phrase", "Bài 01", "ຍິນດີທີ່ໄດ້ຮູ້ຈັກເຈົ້າ", "Rất vui được quen bạn"),
    ("ເຈົ້າຊື່ຫຍັງ", "Bạn tên là gì?", "What is your name?", "chao-seu-nyang", "phrase", "Bài 01", "ເຈົ້າຊື່ຫຍັງເກາະ", "Bạn tên là gì nhỉ"),
    ("ຂ້ອຍຊື່", "Tôi tên là...", "My name is...", "khoy-seu", "phrase", "Bài 01", "ຂ້ອຍຊື່ສົມສີ", "Tôi tên là Somsee"),
    ("ເຈົ້າ", "Bạn / Anh / Chị / Vâng", "You / Yes (polite)", "chao", "pronoun", "Bài 01", "ເຈົ້າແມ່ນໃຜ", "Bạn là ai"),
    ("ຂ້ອຍ", "Tôi", "I / Me", "khoy", "pronoun", "Bài 01", "ຂ້ອຍຮັກເຈົ້າ", "Tôi yêu bạn"),
    ("ລາວ", "Anh ấy / Cô ấy / Lào", "He / She / Lao", "lao", "pronoun", "Bài 01", "ລາວມາແຕ່ໃສ", "Cô ấy đến từ đâu"),
    ("ເພິ່ນ", "Ngài / Ông ấy (kính trọng)", "He / She (polite)", "phoen", "pronoun", "Bài 01", "ເພິ່ນເປັນອາຈານ", "Thầy ấy là giáo viên"),
    ("ພວກເຈົ້າ", "Các bạn", "You (plural)", "phuak-chao", "pronoun", "Bài 01", "ພວກເຈົ້າສະບາຍດີບໍ", "Các bạn khỏe không"),
    ("ພວກເຮົາ", "Chúng tôi / Chúng ta", "We / Us", "phuak-hao", "pronoun", "Bài 01", "ພວກເຮົາໄປນຳກັນ", "Chúng ta cùng đi"),
    ("ພວກເຂົາ", "Họ / Bọn họ", "They / Them", "phuak-khao", "pronoun", "Bài 01", "ພວກເຂົາແມ່ນໃຜ", "Họ là ai"),
    ("ແມ່ນ", "Là / Đúng", "Yes / To be", "maen", "verb", "Bài 01", "ແມ່ນແລ້ວ", "Đúng rồi"),
    ("ບໍ່ແມ່ນ", "Không phải", "No / Not to be", "baw-maen", "phrase", "Bài 01", "ບໍ່ແມ່ນຂ້ອຍ", "Không phải tôi"),
    ("ຊື່", "Tên / Gọi là", "Name / Called", "seu", "noun", "Bài 01", "ຊື່ຂອງເຈົ້າ", "Tên của bạn"),
    ("ນາມສະກຸນ", "Họ (tên họ)", "Surname / Last name", "naam-sa-kun", "noun", "Bài 01", "ນາມສະກຸນຫຍັງ", "Họ là gì"),
    ("ມາແຕ່", "Đến từ", "Come from", "maa-tae", "verb", "Bài 01", "ຂ້ອຍມາແຕ່ຫວຽດນາມ", "Tôi đến từ Việt Nam"),
    ("ຫວຽດນາມ", "Việt Nam", "Vietnam", "viet-naam", "noun", "Bài 01", "ປະເທດຫວຽດນາມ", "Đất nước Việt Nam"),
    ("ລາວ", "Lào", "Laos", "lao", "noun", "Bài 01", "ປະເທດລາວ", "Đất nước Lào"),
    ("ໄທ", "Thái Lan", "Thailand", "thai", "noun", "Bài 01", "ຄົນໄທ", "Người Thái"),
    ("ຈີນ", "Trung Quốc", "China", "jeen", "noun", "Bài 01", "ຄົນຈີນ", "Người Trung Quốc"),
    ("ອາເມລິກາ", "Nước Mỹ", "America / USA", "aa-me-li-kaa", "noun", "Bài 01", "ຄົນອາເມລິກາ", "Người Mỹ"),
    ("ຝຣັ່ງ", "Pháp / Người Tây", "France / Westerner", "fa-rang", "noun", "Bài 01", "ປະເທດຝຣັ່ງ", "Nước Pháp"),
    ("ຍີ່ປຸ່ນ", "Nhật Bản", "Japan", "yee-pun", "noun", "Bài 01", "ຄົນຍີ່ປຸ່ນ", "Người Nhật Bản"),
    ("ເກົາຫຼີ", "Hàn Quốc", "Korea", "kao-lee", "noun", "Bài 01", "ປະເທດເກົາຫຼີ", "Nước Hàn Quốc"),
    ("ຄົນ", "Người", "Person / People", "khon", "noun", "Bài 01", "ຄົນລາວ", "Người Lào"),
    ("ປະເທດ", "Đất nước / Quốc gia", "Country / Nation", "pa-thet", "noun", "Bài 01", "ປະເທດຂອງຂ້ອຍ", "Đất nước của tôi"),
    ("ພາສາ", "Ngôn ngữ / Tiếng", "Language", "phaa-saa", "noun", "Bài 01", "ພາສາລາວ", "Tiếng Lào"),
    ("ພາສາລາວ", "Tiếng Lào", "Lao language", "phaa-saa-lao", "noun", "Bài 01", "ຂ້ອຍຮຽນພາສາລາວ", "Tôi học tiếng Lào"),
    ("ພາສາຫວຽດ", "Tiếng Việt", "Vietnamese language", "phaa-saa-viet", "noun", "Bài 01", "ເຈົ້າເວົ້າພາສາຫວຽດໄດ້ບໍ", "Bạn nói tiếng Việt được không"),
    ("ພາສາອັງກິດ", "Tiếng Anh", "English language", "phaa-saa-ang-kit", "noun", "Bài 01", "ພາສາອັງກິດຍາກ", "Tiếng Anh khó"),
    ("ເວົ້າ", "Nói", "To speak / To talk", "vao", "verb", "Bài 01", "ເວົ້າພາສາລາວ", "Nói tiếng Lào"),
    ("ໄດ້", "Được / Có thể", "Can / To get", "dai", "verb", "Bài 01", "ເວົ້າໄດ້ໜ້ອຍໜຶ່ງ", "Nói được một chút"),
    ("ໜ້ອຍໜຶ່ງ", "Một chút / Một ít", "A little bit", "noy-neung", "adverb", "Bài 01", "ຂ້ອຍເຂົ້າໃຈໜ້ອຍໜຶ່ງ", "Tôi hiểu một chút"),
    ("ເຂົ້າໃຈ", "Hiểu", "To understand", "khao-chai", "verb", "Bài 01", "ເຈົ້າເຂົ້າໃຈບໍ", "Bạn có hiểu không"),
    ("ບໍ່ເຂົ້າໃຈ", "Không hiểu", "Don't understand", "baw-khao-chai", "phrase", "Bài 01", "ຂ້ອຍບໍ່ເຂົ້າໃຈ", "Tôi không hiểu"),
    ("ຊ້າໆ", "Chậm rãi / Từ từ", "Slowly", "xaa-xaa", "adverb", "Bài 01", "ກະລຸນາເວົ້າຊ້າໆ", "Xin hãy nói chậm lại"),
    ("ກະລຸນາ", "Làm ơn / Xin vui lòng", "Please", "ka-lu-naa", "adverb", "Bài 01", "ກະລຸນາຊ່ວຍແດ່", "Làm ơn giúp tôi với"),
    ("ລາກ່ອນ", "Tạm biệt", "Goodbye", "laa-kawn", "phrase", "Bài 01", "ລາກ່ອນເດີ", "Tạm biệt nhé"),
    ("ພົບກັນໃໝ່", "Hẹn gặp lại", "See you again", "phop-kan-mai", "phrase", "Bài 01", "ມື້ອື່ນພົບກັນໃໝ່", "Ngày mai gặp lại"),

    # =========================================================================
    # BÀI 2: GIA ĐÌNH & NGƯỜI THÂN (FAMILY & RELATIVES) - 45 entries
    # =========================================================================
    ("ຄອບຄົວ", "Gia đình", "Family", "khawp-khua", "noun", "Bài 02", "ຄອບຄົວຂອງຂ້ອຍ", "Gia đình của tôi"),
    ("ພໍ່", "Bố / Cha", "Father", "phaw", "noun", "Bài 02", "ພໍ່ຂອງຂ້ອຍໃຈດີ", "Bố tôi rất hiền"),
    ("ແມ່", "Mẹ", "Mother", "mae", "noun", "Bài 02", "ແມ່ຮັກລູກ", "Mẹ yêu con"),
    ("ພໍ່ແມ່", "Bố mẹ / Cha mẹ", "Parents", "phaw-mae", "noun", "Bài 02", "ພໍ່ແມ່ຢູ່ໃສ", "Bố mẹ ở đâu"),
    ("ລູກ", "Con", "Child", "luuk", "noun", "Bài 02", "ລູກຮັກ", "Con yêu"),
    ("ລູກຊາຍ", "Con trai", "Son", "luuk-xaai", "noun", "Bài 02", "ລາວມີລູກຊາຍ", "Anh ấy có con trai"),
    ("ລູກສາວ", "Con gái", "Daughter", "luuk-saao", "noun", "Bài 02", "ລູກສາວງາມຫຼາຍ", "Con gái rất xinh"),
    ("ອ້າຍ", "Anh trai", "Older brother", "aai", "noun", "Bài 02", "ອ້າຍຂອງຂ້ອຍ", "Anh trai tôi"),
    ("ເອື້ອຍ", "Chị gái", "Older sister", "euay", "noun", "Bài 02", "ເອື້ອຍໃຈດີ", "Chị gái tốt bụng"),
    ("ນ້ອງ", "Em", "Younger sibling", "nawng", "noun", "Bài 02", "ນ້ອງຮັກ", "Em yêu quý"),
    ("ນ້ອງຊາຍ", "Em trai", "Younger brother", "nawng-xaai", "noun", "Bài 02", "ນ້ອງຊາຍຮຽນເກັ່ງ", "Em trai học giỏi"),
    ("ນ້ອງສາວ", "Em gái", "Younger sister", "nawng-saao", "noun", "Bài 02", "ນ້ອງສາວນ້ອຍ", "Em gái nhỏ"),
    ("ປູ່", "Ông nội", "Paternal grandfather", "puu", "noun", "Bài 02", "ປູ່ມີອາຍຸຫຼາຍ", "Ông nội cao tuổi"),
    ("ຍ່າ", "Bà nội", "Paternal grandmother", "yaa", "noun", "Bài 02", "ຍ່າໃຈດີ", "Bà nội hiền từ"),
    ("ພໍ່ເຖົ້າ", "Ông ngoại", "Maternal grandfather", "phaw-thao", "noun", "Bài 02", "ພໍ່ເຖົ້າຢູ່ບ້ານ", "Ông ngoại ở nhà"),
    ("ແມ່ເຖົ້າ", "Bà ngoại", "Maternal grandmother", "mae-thao", "noun", "Bài 02", "ແມ່ເຖົ້າເຮັດອາຫານ", "Bà ngoại nấu ăn"),
    ("ລຸງ", "Bác trai", "Uncle (older)", "lung", "noun", "Bài 02", "ລຸງມາຢາມ", "Bác trai đến thăm"),
    ("ປ້າ", "Bác gái", "Aunt (older)", "paa", "noun", "Bài 02", "ປ້າຂາຍເຄື່ອງ", "Bác gái bán hàng"),
    ("ອາວ", "Chú (em trai của bố)", "Uncle (father's younger brother)", "aao", "noun", "Bài 02", "ອາວຢູ່ໄກ", "Chú ở xa"),
    ("ອາ", "Cô (em gái của bố)", "Aunt (father's younger sister)", "aa", "noun", "Bài 02", "ອາມາແຕ່ໃສ", "Cô đến từ đâu"),
    ("ນ້າບ່າວ", "Cậu (em trai của mẹ)", "Uncle (mother's younger brother)", "naa-baao", "noun", "Bài 02", "ນ້າບ່າວໄປວຽກ", "Cậu đi làm"),
    ("ນ້າສາວ", "Dì (em gái của mẹ)", "Aunt (mother's younger sister)", "naa-saao", "noun", "Bài 02", "ນ້າສາວງາມ", "Dì rất đẹp"),
    ("ຫຼານ", "Cháu", "Niece / Nephew / Grandchild", "laan", "noun", "Bài 02", "ຫຼານນ້ອຍ", "Cháu bé"),
    ("ຫຼານຊາຍ", "Cháu trai", "Nephew / Grandson", "laan-xaai", "noun", "Bài 02", "ຫຼານຊາຍສະຫຼາດ", "Cháu trai thông minh"),
    ("ຫຼານສາວ", "Cháu gái", "Niece / Granddaughter", "laan-saao", "noun", "Bài 02", "ຫຼານສາວໜ້າຮັກ", "Cháu gái đáng yêu"),
    ("ຜົວ", "Chồng", "Husband", "phua", "noun", "Bài 02", "ຜົວເມຍ", "Vợ chồng"),
    ("ເມຍ", "Vợ", "Wife", "mia", "noun", "Bài 02", "ເມຍຂອງລາວ", "Vợ của anh ấy"),
    ("ແຕ່ງງານ", "Kết hôn / Cưới", "To marry / Marriage", "taeng-ngaan", "verb", "Bài 02", "ແຕ່ງງານແລ້ວບໍ", "Đã kết hôn chưa"),
    ("ໂສດ", "Độc thân", "Single", "sot", "adjective", "Bài 02", "ຂ້ອຍຍັງໂສດ", "Tôi vẫn độc thân"),
    ("ມີ", "Có", "To have", "mee", "verb", "Bài 02", "ມີລູກຈັກຄົນ", "Có mấy người con"),
    ("ບໍ່ມີ", "Không có", "Don't have", "baw-mee", "verb", "Bài 02", "ບໍ່ມີເງິນ", "Không có tiền"),
    ("ອາຍຸ", "Tuổi", "Age", "aa-yu", "noun", "Bài 02", "ເຈົ້າອາຍຸຈັກປີ", "Bạn bao nhiêu tuổi"),
    ("ປີ", "Năm / Tuổi", "Year / Years old", "pee", "noun", "Bài 02", "ຂ້ອຍອາຍຸຊາວປີ", "Tôi hai mươi tuổi"),
    ("ຢູ່", "Ở / Sống tại", "To stay / To live", "yuu", "verb", "Bài 02", "ເຈົ້າຢູ່ໃສ", "Bạn ở đâu"),
    ("ບ້ານ", "Làng / Nhà", "Village / Home", "baan", "noun", "Bài 02", "ບ້ານເກີດ", "Quê hương / Nhà sinh"),
    ("ເຮືອນ", "Ngôi nhà", "House", "heuan", "noun", "Bài 02", "ເຮືອນຂອງຂ້ອຍ", "Nhà của tôi"),
    ("ຮັກ", "Yêu", "To love", "hak", "verb", "Bài 02", "ຂ້ອຍຮັກຄອບຄົວ", "Tôi yêu gia đình"),
    ("ຊ່ວຍ", "Giúp đỡ", "To help", "xuay", "verb", "Bài 02", "ຊ່ວຍຂ້ອຍແດ່", "Giúp tôi với"),
    ("ໃຈດີ", "Tốt bụng / Hiền lành", "Kind / Good-natured", "chai-dee", "adjective", "Bài 02", "ຄົນລາວໃຈດີ", "Người Lào rất hiền"),
    ("ງາມ", "Đẹp", "Beautiful", "ngaam", "adjective", "Bài 02", "ດອກໄມ້ງາມ", "Hoa đẹp"),
    ("ໜ້າຮັກ", "Đáng yêu", "Cute / Lovely", "naa-hak", "adjective", "Bài 02", "ເດັກນ້ອຍໜ້າຮັກ", "Trẻ nhỏ đáng yêu"),
    ("ສະຫຼາດ", "Thông minh", "Smart / Intelligent", "sa-laat", "adjective", "Bài 02", "ນັກຮຽນສະຫຼາດ", "Học sinh thông minh"),
    ("ສູງ", "Cao", "Tall / High", "suung", "adjective", "Bài 02", "ລາວສູງຫຼາຍ", "Anh ấy rất cao"),
    ("ເຕ້ຍ", "Thấp / Lùn", "Short", "tia", "adjective", "Bài 02", "ຄົນເຕ້ຍ", "Người thấp"),
    ("ຕຸ້ຍ", "Béo / Mập", "Fat / Chubby", "tuy", "adjective", "Bài 02", "ລາວຕຸ້ຍ", "Cậu ấy mập mạp"),

    # =========================================================================
    # BÀI 3: CHỮ SỐ & SỐ ĐẾM (NUMBERS & QUANTIFIERS) - 45 entries
    # =========================================================================
    ("ສູນ", "Không (số 0)", "Zero (0)", "suun", "number", "Bài 03", "ເລກສູນ", "Số không"),
    ("ໜຶ່ງ", "Một (số 1)", "One (1)", "neung", "number", "Bài 03", "ໜຶ່ງອັນ", "Một cái"),
    ("ສອງ", "Hai (số 2)", "Two (2)", "sawng", "number", "Bài 03", "ສອງຄົນ", "Hai người"),
    ("ສາມ", "Ba (số 3)", "Three (3)", "saam", "number", "Bài 03", "ສາມມື້", "Ba ngày"),
    ("ສີ່", "Bốn (số 4)", "Four (4)", "see", "number", "Bài 03", "ສີ່ໂມງ", "Bốn giờ"),
    ("ຫ້າ", "Năm (số 5)", "Five (5)", "haa", "number", "Bài 03", "ຫ້າພັນ", "Năm nghìn"),
    ("ຫົກ", "Sáu (số 6)", "Six (6)", "hok", "number", "Bài 03", "ຫົກເດືອນ", "Sáu tháng"),
    ("ເຈັດ", "Bảy (số 7)", "Seven (7)", "chet", "number", "Bài 03", "ເຈັດວັນ", "Bảy ngày"),
    ("ແປດ", "Tám (số 8)", "Eight (8)", "paet", "number", "Bài 03", "ແປດໂມງ", "Tám giờ"),
    ("ເກົ້າ", "Chín (số 9)", "Nine (9)", "kao", "number", "Bài 03", "ເກົ້າສິບ", "Chín mươi"),
    ("ສິບ", "Mười (số 10)", "Ten (10)", "sip", "number", "Bài 03", "ສິບຄົນ", "Mười người"),
    ("ສິບເອັດ", "Mười một (số 11)", "Eleven (11)", "sip-et", "number", "Bài 03", "ສິບເອັດໂມງ", "Mười một giờ"),
    ("ສິບສອງ", "Mười hai (số 12)", "Twelve (12)", "sip-sawng", "number", "Bài 03", "ສິບສອງເດືອນ", "Mười hai tháng"),
    ("ສິບສາມ", "Mười ba (số 13)", "Thirteen (13)", "sip-saam", "number", "Bài 03", "ສິບສາມປີ", "Mười ba năm"),
    ("ຊາວ", "Hai mươi (số 20)", "Twenty (20)", "xaao", "number", "Bài 03", "ຊາວພັນ", "Hai mươi nghìn"),
    ("ຊາວເອັດ", "Hai mươi mốt (số 21)", "Twenty-one (21)", "xaao-et", "number", "Bài 03", "ວັນທີຊາວເອັດ", "Ngày hai mươi mốt"),
    ("ສາມສິບ", "Ba mươi (số 30)", "Thirty (30)", "saam-sip", "number", "Bài 03", "ສາມສິບມື້", "Ba mươi ngày"),
    ("ສີ່ສິບ", "Bốn mươi (số 40)", "Forty (40)", "see-sip", "number", "Bài 03", "ສີ່ສິບກິໂລ", "Bốn mươi cân"),
    ("ຫ້າສິບ", "Năm mươi (số 50)", "Fifty (50)", "haa-sip", "number", "Bài 03", "ຫ້າສິບເປີເຊັນ", "Năm mươi phần trăm"),
    ("ຮ້ອຍ", "Trăm (100)", "Hundred (100)", "hwy", "number", "Bài 03", "ໜຶ່ງຮ້ອຍ", "Một trăm"),
    ("ພັນ", "Nghìn (1,000)", "Thousand (1,000)", "phan", "number", "Bài 03", "ສິບພັນ", "Mười nghìn"),
    ("ໝື່ນ", "Mười nghìn (10,000)", "Ten thousand (10,000)", "meun", "number", "Bài 03", "ໜຶ່ງໝື່ນກີບ", "Một vạn kíp"),
    ("ແສນ", "Trăm nghìn (100,000)", "Hundred thousand (100,000)", "saen", "number", "Bài 03", "ໜຶ່ງແສນກີບ", "Một trăm nghìn kíp"),
    ("ລ້ານ", "Triệu (1,000,000)", "Million (1,000,000)", "laan", "number", "Bài 03", "ໜຶ່ງລ້ານກີບ", "Một triệu kíp"),
    ("ຕື້", "Tỷ (1,000,000,000)", "Billion (1,000,000,000)", "teu", "number", "Bài 03", "ໜຶ່ງຕື້", "Một tỷ"),
    ("ເລກ", "Con số / Chữ số", "Number / Digit", "lek", "noun", "Bài 03", "ເລກໂທລະສັບ", "Số điện thoại"),
    ("ເບີ", "Số (hiệu)", "Number (phone/room)", "ber", "noun", "Bài 03", "ເບີຫ້ອງ", "Số phòng"),
    ("ຈັກ", "Mấy / Bao nhiêu", "How many / How much", "chak", "pronoun", "Bài 03", "ຈັກໂມງແລ້ວ", "Mấy giờ rồi"),
    ("ເທົ່າໃດ", "Bao nhiêu", "How much", "thao-dai", "pronoun", "Bài 03", "ລາຄາເທົ່າໃດ", "Giá bao nhiêu"),
    ("ອັນ", "Cái / Chiếc (loại từ)", "Item / Thing (classifier)", "an", "noun", "Bài 03", "ອັນນີ້", "Cái này"),
    ("ຄົນ", "Người (loại từ)", "Person (classifier)", "khon", "noun", "Bài 03", "ສາມຄົນ", "Ba người"),
    ("ໂຕ", "Con / Chiếc áo (loại từ)", "Animal / Shirt (classifier)", "toh", "noun", "Bài 03", "ໝາສອງໂຕ", "Hai con chó"),
    ("ຫົວ", "Cuốn / Quyển / Củ", "Book / Bulb (classifier)", "hua", "noun", "Bài 03", "ປຶ້ມສາມຫົວ", "Ba quyển sách"),
    ("ກ້ອນ", "Hòn / Cục / Viên", "Lump / Piece (classifier)", "kawn", "noun", "Bài 03", "ຫີນໜຶ່ງກ້ອນ", "Một hòn đá"),
    ("ແກ້ວ", "Chai / Lọ", "Bottle / Glass", "kaew", "noun", "Bài 03", "ນ້ຳໜຶ່ງແກ້ວ", "Một chai nước"),
    ("ຈອກ", "Cốc / Ly", "Cup / Mug", "chawk", "noun", "Bài 03", "ກາເຟສອງຈອກ", "Hai cốc cà phê"),
    ("ຖ້ວຍ", "Bát / Chén", "Bowl", "thuay", "noun", "Bài 03", "ເຂົ້າໜຶ່ງຖ້ວຍ", "Một bát cơm"),
    ("ຈານ", "Đĩa", "Plate", "chaan", "noun", "Bài 03", "ຈານໃຫຍ່", "Cái đĩa lớn"),
    ("ບ່ວງ", "Thìa / Muỗng", "Spoon", "buang", "noun", "Bài 03", "ບ່ວງໜຶ່ງອັນ", "Một cái thìa"),
    ("ສ້ອມ", "Nĩa / Dĩa", "Fork", "sawm", "noun", "Bài 03", "ບ່ວງແລະສ້ອມ", "Thìa và nĩa"),
    ("ມີດ", "Dao", "Knife", "meet", "noun", "Bài 03", "ມີດແຫຼມ", "Dao sắc"),
    ("ຫຼາຍ", "Nhiều", "Many / Much", "lai", "adjective", "Bài 03", "ຄົນຫຼາຍ", "Nhiều người"),
    ("ໜ້ອຍ", "Ít", "Few / Little", "noy", "adjective", "Bài 03", "ມີເງິນໜ້ອຍ", "Có ít tiền"),
    ("ທັງໝົດ", "Tất cả / Toàn bộ", "All / Total", "thang-mot", "adverb", "Bài 03", "ທັງໝົດເທົ່າໃດ", "Tất cả bao nhiêu"),
    ("ເຄິ່ງ", "Nửa / Một nửa", "Half", "khoeng", "noun", "Bài 03", "ເຄິ່ງຊົ່ວໂມງ", "Nửa giờ"),

    # =========================================================================
    # BÀI 4: THỜI GIAN, NGÀY THÁNG & THỨ (TIME & CALENDAR) - 45 entries
    # =========================================================================
    ("ເວລາ", "Thời gian", "Time", "ve-laa", "noun", "Bài 04", "ບໍ່ມີເວລາ", "Không có thời gian"),
    ("ໂມງ", "Giờ / Đồng hồ", "O'clock / Watch", "moong", "noun", "Bài 04", "ຕອນນີ້ຈັກໂມງ", "Bây giờ mấy giờ"),
    ("ນາທີ", "Phút", "Minute", "naa-thee", "noun", "Bài 04", "ສິບຫ້ານາທີ", "Mười lăm phút"),
    ("ວິນາທີ", "Giây", "Second", "vi-naa-thee", "noun", "Bài 04", "ຫົກສິບວິນາທີ", "Sáu mươi giây"),
    ("ຊົ່ວໂມງ", "Tiếng đồng hồ", "Hour (duration)", "xua-moong", "noun", "Bài 04", "ສອງຊົ່ວໂມງ", "Hai tiếng đồng hồ"),
    ("ມື້", "Ngày", "Day", "meu", "noun", "Bài 04", "ມື້ນີ້", "Hôm nay"),
    ("ວັນ", "Ngày (trang trọng)", "Day (formal)", "van", "noun", "Bài 04", "ວັນທີໜຶ່ງ", "Ngày mùng một"),
    ("ມື້ນີ້", "Hôm nay", "Today", "meu-nee", "noun", "Bài 04", "ມື້ນີ້ອາກາດດີ", "Hôm nay thời tiết đẹp"),
    ("ມື້ອື່ນ", "Ngày mai", "Tomorrow", "meu-eun", "noun", "Bài 04", "ມື້ອື່ນໄປໃສ", "Ngày mai đi đâu"),
    ("ມື້ວານນີ້", "Hôm qua", "Yesterday", "meu-vaan-nee", "noun", "Bài 04", "ມື້ວານນີ້ຂ້ອຍຢູ່ບ້ານ", "Hôm qua tôi ở nhà"),
    ("ມື້ຮື", "Ngày kia", "Day after tomorrow", "meu-heu", "noun", "Bài 04", "ມື້ຮືພົບກັນ", "Ngày kia gặp lại"),
    ("ອາທິດ", "Tuần", "Week", "aa-thit", "noun", "Bài 04", "ອາທິດນີ້", "Tuần này"),
    ("ອາທິດໜ້າ", "Tuần sau / Tuần tới", "Next week", "aa-thit-naa", "noun", "Bài 04", "ອາທິດໜ້າຮຽນ", "Tuần sau học"),
    ("ອາທິດແລ້ວ", "Tuần trước", "Last week", "aa-thit-laew", "noun", "Bài 04", "ອາທິດແລ້ວໄປທ່ຽວ", "Tuần trước đi chơi"),
    ("ເດືອນ", "Tháng / Mặt trăng", "Month / Moon", "deuan", "noun", "Bài 04", "ເດືອນນີ້", "Tháng này"),
    ("ເດືອນໜ້າ", "Tháng sau", "Next month", "deuan-naa", "noun", "Bài 04", "ເດືອນໜ້າສອບເສັງ", "Tháng sau thi"),
    ("ເດືອນແລ້ວ", "Tháng trước", "Last month", "deuan-laew", "noun", "Bài 04", "ເດືອນແລ້ວຮ້ອນ", "Tháng trước nóng"),
    ("ປີ", "Năm", "Year", "pee", "noun", "Bài 04", "ປີນີ້", "Năm nay"),
    ("ປີໜ້າ", "Năm sau", "Next year", "pee-naa", "noun", "Bài 04", "ປີໜ້າກັບບ້ານ", "Năm sau về nhà"),
    ("ປີກາຍ", "Năm ngoái", "Last year", "pee-kaai", "noun", "Bài 04", "ປີກາຍໄປວຽງຈັນ", "Năm ngoái đi Vientiane"),
    ("ວັນຈັນ", "Thứ Hai", "Monday", "van-chan", "noun", "Bài 04", "ວັນຈັນໄປຮຽນ", "Thứ Hai đi học"),
    ("ວັນອັງຄານ", "Thứ Ba", "Tuesday", "van-ang-khaan", "noun", "Bài 04", "ວັນອັງຄານເຮັດວຽກ", "Thứ Ba làm việc"),
    ("ວັນພຸດ", "Thứ Tư", "Wednesday", "van-phut", "noun", "Bài 04", "ວັນພຸດພົບກັນ", "Thứ Tư gặp nhau"),
    ("ວັນພະຫັດ", "Thứ Năm", "Thursday", "van-pha-hat", "noun", "Bài 04", "ວັນພະຫັດວ່າງ", "Thứ Năm rảnh"),
    ("ວັນສຸກ", "Thứ Sáu", "Friday", "van-suk", "noun", "Bài 04", "ວັນສຸກຕອນແລງ", "Chiều thứ Sáu"),
    ("ວັນເສົາ", "Thứ Bảy", "Saturday", "van-sao", "noun", "Bài 04", "ວັນເສົາພັກຜ່ອນ", "Thứ Bảy nghỉ ngơi"),
    ("ວັນອາທິດ", "Chủ Nhật", "Sunday", "van-aa-thit", "noun", "Bài 04", "ວັນອາທິດໄປວັດ", "Chủ Nhật đi chùa"),
    ("ຕອນເຊົ້າ", "Buổi sáng", "Morning", "tawn-xao", "noun", "Bài 04", "ຕອນເຊົ້າກິນເຂົ້າ", "Buổi sáng ăn cơm"),
    ("ຕອນສວາຍ", "Buổi trưa", "Noon / Afternoon", "tawn-suay", "noun", "Bài 04", "ຕອນສວາຍຮ້ອນ", "Buổi trưa nóng"),
    ("ຕອນແລງ", "Buổi chiều / Buổi tối", "Evening", "tawn-laeng", "noun", "Bài 04", "ຕອນແລງໄປຕະຫຼາດ", "Buổi chiều đi chợ"),
    ("ຕອນກາງຄືນ", "Ban đêm", "Night time", "tawn-kaang-kheun", "noun", "Bài 04", "ຕອນກາງຄືນນອນ", "Ban đêm ngủ"),
    ("ຕອນນີ້", "Bây giờ / Hiện tại", "Now / Currently", "tawn-nee", "adverb", "Bài 04", "ຕອນນີ້ເຮັດຫຍັງ", "Bây giờ làm gì"),
    ("ດຽວນີ້", "Ngay bây giờ", "Right now", "diao-nee", "adverb", "Bài 04", "ດຽວນີ້ໄປເລີຍ", "Đi ngay bây giờ"),
    ("ກ່ອນ", "Trước", "Before", "kawn", "adverb", "Bài 04", "ກິນເຂົ້າກ່ອນ", "Ăn cơm trước"),
    ("ຫຼັງ", "Sau", "After", "lang", "adverb", "Bài 04", "ຫຼັງຈາກນັ້ນ", "Sau đó"),
    ("ເຊົ້າ", "Sớm / Sáng", "Early / Morning", "xao", "adjective", "Bài 04", "ຕື່ນເຊົ້າ", "Thức dậy sớm"),
    ("ຊ້າ", "Muộn / Trễ", "Late / Slow", "xaa", "adjective", "Bài 04", "ມາວຽກຊ້າ", "Đến làm muộn"),
    ("ໄວ", "Nhanh", "Fast / Quick", "vai", "adjective", "Bài 04", "ໄປໄວໆ", "Đi nhanh lên"),
    ("ທັນ", "Kịp", "In time", "than", "verb", "Bài 04", "ທັນເວລາ", "Kịp giờ"),
    ("ບໍ່ທັນ", "Không kịp", "Not in time", "baw-than", "phrase", "Bài 04", "ບໍ່ທັນລົດ", "Không kịp xe"),
    ("ວັນພັກ", "Ngày nghỉ", "Holiday / Day off", "van-phak", "noun", "Bài 04", "ມື້ນີ້ແມ່ນວັນພັກ", "Hôm nay là ngày nghỉ"),
    ("ປີໃໝ່", "Năm mới", "New Year", "pee-mai", "noun", "Bài 04", "ສະບາຍດີປີໃໝ່", "Chúc mừng năm mới"),
    ("ບຸນ", "Lễ hội / Phúc đức", "Festival / Merit", "bun", "noun", "Bài 04", "ບຸນປີໃໝ່ລາວ", "Tết Lào (Bun Pi May)"),
    ("ວັນເກີດ", "Sinh nhật", "Birthday", "van-koet", "noun", "Bài 04", "ສຸກສັນວັນເກີດ", "Chúc mừng sinh nhật"),
    ("ສະເຫຼີມສະຫຼອງ", "Kỷ niệm / Ăn mừng", "To celebrate", "sa-loem-sa-lawng", "verb", "Bài 04", "ສະເຫຼີມສະຫຼອງປີໃໝ່", "Ăn mừng năm mới"),

    # =========================================================================
    # BÀI 5: TRƯỜNG HỌC & ĐỒ DÙNG HỌC TẬP (SCHOOL & STUDY) - 45 entries
    # =========================================================================
    ("ໂຮງຮຽນ", "Trường học", "School", "hong-hian", "noun", "Bài 05", "ໂຮງຮຽນໃຫຍ່", "Trường học to lớn"),
    ("ມະຫາວິທະຍາໄລ", "Trường đại học", "University", "ma-haa-vit-tha-nyaa-lai", "noun", "Bài 05", "ມະຫາວິທະຍາໄລແຫ່ງຊາດ", "Đại học Quốc gia"),
    ("ຫ້ອງຮຽນ", "Lớp học / Phòng học", "Classroom", "hong-hian", "noun", "Bài 05", "ຢູ່ໃນຫ້ອງຮຽນ", "Ở trong lớp học"),
    ("ຫ້ອງສະໝຸດ", "Thư viện", "Library", "hong-sa-mut", "noun", "Bài 05", "ໄປຫ້ອງສະໝຸດ", "Đi thư viện"),
    ("ຄູ", "Thầy giáo / Cô giáo", "Teacher", "khuu", "noun", "Bài 05", "ຄູສອນໜັງສື", "Thầy giáo dạy chữ"),
    ("ອາຈານ", "Giảng viên / Thầy", "Professor / Teacher", "aa-chaan", "noun", "Bài 05", "ອາຈານໃຈດີ", "Giảng viên hiền"),
    ("ນັກຮຽນ", "Học sinh", "Student / Pupil", "nak-hian", "noun", "Bài 05", "ນັກຮຽນຕັ້ງໃຈ", "Học sinh chăm chỉ"),
    ("ນັກສຶກສາ", "Sinh viên", "University student", "nak-seuk-saa", "noun", "Bài 05", "ນັກສຶກສາລາວ", "Sinh viên Lào"),
    ("ເພື່ອນ", "Bạn bè", "Friend", "pheuan", "noun", "Bài 05", "ເພື່ອນສະໜິດ", "Bạn thân"),
    ("ໝູ່", "Bạn / Bè bạn", "Friend / Companion", "muu", "noun", "Bài 05", "ໝູ່ຮ່ວມຫ້ອງ", "Bạn cùng lớp"),
    ("ຮຽນ", "Học", "To study / To learn", "hian", "verb", "Bài 05", "ຮຽນໜັງສື", "Học chữ / Học bài"),
    ("ສອນ", "Dạy", "To teach", "sawn", "verb", "Bài 05", "ສອນພາສາລາວ", "Dạy tiếng Lào"),
    ("ອ່ານ", "Đọc", "To read", "aan", "verb", "Bài 05", "ອ່ານປຶ້ມ", "Đọc sách"),
    ("ຂຽນ", "Viết", "To write", "khian", "verb", "Bài 05", "ຂຽນໜັງສື", "Viết chữ"),
    ("ຟັງ", "Nghe", "To listen", "fang", "verb", "Bài 05", "ຟັງອາຈານ", "Nghe giảng viên"),
    ("ຖາມ", "Hỏi", "To ask", "thaam", "verb", "Bài 05", "ຖາມຄຳຖາມ", "Hỏi câu hỏi"),
    ("ຕອບ", "Trả lời", "To answer", "tawp", "verb", "Bài 05", "ຕອບຄຳຖາມ", "Trả lời câu hỏi"),
    ("ປຶ້ມ", "Sách / Vở", "Book / Notebook", "peum", "noun", "Bài 05", "ປຶ້ມແບບຮຽນ", "Sách giáo khoa"),
    ("ປຶ້ມຂຽນ", "Vở viết", "Notebook", "peum-khian", "noun", "Bài 05", "ຂຽນໃສ່ປຶ້ມຂຽນ", "Viết vào vở"),
    ("ສໍ", "Bút chì", "Pencil", "saw", "noun", "Bài 05", "ສໍດຳ", "Bút chì đen"),
    ("ບິກ", "Bút bi", "Pen", "bik", "noun", "Bài 05", "ບິກສີຟ້າ", "Bút bi màu xanh"),
    ("ຢາງລຶບ", "Cục tẩy / Cục gôm", "Eraser", "yaang-leup", "noun", "Bài 05", "ໃຊ້ຢາງລຶບ", "Dùng cục tẩy"),
    ("ໄມ້ບັນທັດ", "Thước kẻ", "Ruler", "mai-ban-that", "noun", "Bài 05", "ໄມ້ບັນທັດຍາວ", "Thước kẻ dài"),
    ("ກະເປົາ", "Cặp sách / Túi xách", "Bag / Backpack", "ka-pao", "noun", "Bài 05", "ກະເປົານັກຮຽນ", "Cặp học sinh"),
    ("ໂຕະ", "Cái bàn", "Table / Desk", "toh", "noun", "Bài 05", "ໂຕະຮຽນ", "Bàn học"),
    ("ຕັ່ງ", "Cái ghế", "Chair", "tang", "noun", "Bài 05", "ນັ່ງຕັ່ງ", "Ngồi ghế"),
    ("ກະດານ", "Bảng viết", "Blackboard / Board", "ka-daan", "noun", "Bài 05", "ຂຽນໃສ່ກະດານ", "Viết lên bảng"),
    ("ສອກກະດານ", "Phấn viết bảng", "Chalk", "saw-ka-daan", "noun", "Bài 05", "ສອກກະດານຂາວ", "Phấn trắng"),
    ("ບົດຮຽນ", "Bài học", "Lesson", "bot-hian", "noun", "Bài 05", "ບົດຮຽນທີໜຶ່ງ", "Bài học số một"),
    ("ການບ້ານ", "Bài tập về nhà", "Homework", "kaan-baan", "noun", "Bài 05", "ເຮັດການບ້ານ", "Làm bài tập về nhà"),
    ("ສອບເສັງ", "Thi cử", "Exam / Test", "sawp-seng", "verb", "Bài 05", "ມື້ອື່ນສອບເສັງ", "Ngày mai thi"),
    ("ຄະແນນ", "Điểm số", "Score / Mark", "kha-naen", "noun", "Bài 05", "ໄດ້ຄະແນນດີ", "Được điểm tốt"),
    ("ເກັ່ງ", "Giỏi / Xuất sắc", "Good at / Clever", "keng", "adjective", "Bài 05", "ລາວຮຽນເກັ່ງ", "Cậu ấy học giỏi"),
    ("ງ່າຍ", "Dễ", "Easy", "ngaai", "adjective", "Bài 05", "ພາສາລາວງ່າຍ", "Tiếng Lào dễ"),
    ("ຍາກ", "Khó", "Difficult / Hard", "nyaak", "adjective", "Bài 05", "ບົດຮຽນຍາກ", "Bài học khó"),
    ("ເຂົ້າຮຽນ", "Vào học", "To attend class", "khao-hian", "verb", "Bài 05", "ເຂົ້າຮຽນແປດໂມງ", "Vào học lúc 8 giờ"),
    ("ເລີກຮຽນ", "Tan học", "Class dismisses", "loek-hian", "verb", "Bài 05", "ເລີກຮຽນສີ່ໂມງ", "Tan học lúc 4 giờ"),
    ("ພັກຜ່ອນ", "Nghỉ giải lao / Nghỉ ngơi", "Break / Rest", "phak-phawn", "verb", "Bài 05", "ພັກຜ່ອນສິບນາທີ", "Nghỉ mười phút"),
    ("ຕັ້ງໃຈ", "Chăm chỉ / Tập trung", "Attentive / Diligent", "tang-chai", "adjective", "Bài 05", "ຕັ້ງໃຈຮຽນ", "Chăm chỉ học tập"),
    ("ຮູ້", "Biết", "To know", "huu", "verb", "Bài 05", "ຂ້ອຍບໍ່ຮູ້", "Tôi không biết"),
    ("ຈື່", "Nhớ", "To remember", "cheu", "verb", "Bài 05", "ຂ້ອຍຈື່ໄດ້", "Tôi nhớ được"),
    ("ລືມ", "Quên", "To forget", "leum", "verb", "Bài 05", "ຢ່າລືມເດີ", "Đừng quên nhé"),
    ("ຄິດ", "Nghĩ / Suy nghĩ", "To think", "khit", "verb", "Bài 05", "ຄິດຮອດ", "Nhớ nhung / Nghĩ đến"),
    ("ຝຶກແອບ", "Luyện tập", "To practice", "feuk-aep", "verb", "Bài 05", "ຝຶກແອບເວົ້າ", "Luyện nói"),
    ("ຄຳສັບ", "Từ vựng", "Vocabulary / Word", "kham-sap", "noun", "Bài 05", "ຮຽນຄຳສັບໃໝ່", "Học từ mới"),

    # =========================================================================
    # BÀI 6: ẨM THỰC & MÓN ĂN LÀO (FOOD & DRINKS) - 45 entries
    # =========================================================================
    ("ກິນ", "Ăn", "To eat", "kin", "verb", "Bài 06", "ກິນເຂົ້າແລ້ວບໍ", "Đã ăn cơm chưa"),
    ("ດື່ມ", "Uống", "To drink", "deum", "verb", "Bài 06", "ດື່ມນ້ຳ", "Uống nước"),
    ("ເຂົ້າ", "Cơm / Gạo", "Rice / Meal", "khao", "noun", "Bài 06", "ກິນເຂົ້າ", "Ăn cơm"),
    ("ເຂົ້ານຽວ", "Xôi (gạo nếp Lào)", "Sticky rice", "khao-niao", "noun", "Bài 06", "ເຂົ້ານຽວແຊບ", "Xôi Lào rất ngon"),
    ("ເຂົ້າຈ້າວ", "Cơm tẻ (gạo tẻ)", "Plain rice", "khao-chao", "noun", "Bài 06", "ກິນເຂົ້າຈ້າວ", "Ăn cơm tẻ"),
    ("ເຂົ້າປຽກ", "Bánh canh / Cháo bánh canh", "Wet noodle soup (Khao Piak)", "khao-piak", "noun", "Bài 06", "ເຂົ້າປຽກໄກ່", "Bánh canh gà"),
    ("ເຂົ້າປຸ້ນ", "Bún", "Rice vermicelli (Khao Poon)", "khao-pun", "noun", "Bài 06", "ເຂົ້າປຸ້ນນ້ຳແຈ່ວ", "Bún nước lèo"),
    ("ເຝີ", "Phở", "Pho noodle soup", "foe", "noun", "Bài 06", "ເຝີຊີ້ນງົວ", "Phở bò"),
    ("ລາບ", "Món Lạp (món ăn quốc hồn Lào)", "Larb (Lao minced meat salad)", "laap", "noun", "Bài 06", "ລາບຊີ້ນ", "Lạp thịt bò"),
    ("ຕຳໝາກຫຸ່ງ", "Nộm đu đủ (Tam Mak Houng)", "Papaya salad", "tam-maak-hung", "noun", "Bài 06", "ຕຳໝາກຫຸ່ງເຜັດ", "Nộm đu đủ cay"),
    ("ແກງ", "Canh / Súp", "Soup / Curry", "kaeng", "noun", "Bài 06", "ແກງໜໍ່ໄມ້", "Canh măng"),
    ("ປີ້ງ", "Nướng", "Grilled / Roasted", "peeng", "verb", "Bài 06", "ປີ້ງໄກ່", "Gà nướng"),
    ("ທອດ", "Chiên / Rán", "Fried", "thawt", "verb", "Bài 06", "ປາທອດ", "Cá rán"),
    ("ຕົ້ມ", "Luộc / Nấu súp", "Boiled / To boil", "tom", "verb", "Bài 06", "ໄຂ່ຕົ້ມ", "Trứng luộc"),
    ("ຊີ້ນ", "Thịt", "Meat", "seen", "noun", "Bài 06", "ຊີ້ນໝູ", "Thịt lợn"),
    ("ຊີ້ນໝູ", "Thịt lợn / Thịt heo", "Pork", "seen-muu", "noun", "Bài 06", "ກິນຊີ້ນໝູ", "Ăn thịt lợn"),
    ("ຊີ້ນງົວ", "Thịt bò", "Beef", "seen-ngua", "noun", "Bài 06", "ລາບຊີ້ນງົວ", "Lạp thịt bò"),
    ("ຊີ້ນໄກ່", "Thịt gà", "Chicken meat", "seen-kai", "noun", "Bài 06", "ປີ້ງໄກ່ແຊບ", "Gà nướng ngon"),
    ("ປາ", "Cá", "Fish", "paa", "noun", "Bài 06", "ກິນປາ", "Ăn cá"),
    ("ກຸ້ງ", "Tôm", "Shrimp / Prawn", "kung", "noun", "Bài 06", "ກຸ້ງເຜົາ", "Tôm nướng"),
    ("ໄຂ່", "Trứng", "Egg", "khai", "noun", "Bài 06", "ໄຂ່ດາວ", "Trứng ốp la"),
    ("ຜັກ", "Rau", "Vegetable", "phak", "noun", "Bài 06", "ຜັກສົດ", "Rau tươi"),
    ("ໝາກໄມ້", "Hoa quả / Trái cây", "Fruit", "maak-mai", "noun", "Bài 06", "ກິນໝາກໄມ້", "Ăn hoa quả"),
    ("ໝາກກ້ວຍ", "Quả chuối", "Banana", "maak-kluay", "noun", "Bài 06", "ໝາກກ້ວຍສຸກ", "Chuối chín"),
    ("ໝາກກ້ຽງ", "Quả cam", "Orange", "maak-kiang", "noun", "Bài 06", "ນ້ຳໝາກກ້ຽງ", "Nước cam ép"),
    ("ໝາກມ່ວງ", "Quả xoài", "Mango", "maak-muang", "noun", "Bài 06", "ໝາກມ່ວງຫວານ", "Xoài ngọt"),
    ("ໝາກໂມ", "Quả dưa hấu", "Watermelon", "maak-moo", "noun", "Bài 06", "ໝາກໂມແດງ", "Dưa hấu đỏ"),
    ("ນ້ຳ", "Nước", "Water", "nam", "noun", "Bài 06", "ນ້ຳດື່ມ", "Nước uống"),
    ("ນ້ຳກ້ອນ", "Nước đá / Đá lạnh", "Ice", "nam-kawn", "noun", "Bài 06", "ເອົານ້ຳກ້ອນ", "Lấy đá lạnh"),
    ("ກາເຟ", "Cà phê", "Coffee", "kaa-fae", "noun", "Bài 06", "ກາເຟລາວ", "Cà phê Lào"),
    ("ຊາ", "Trà / Chè", "Tea", "saa", "noun", "Bài 06", "ດື່ມຊາ", "Uống trà"),
    ("ນົມ", "Sữa", "Milk", "nom", "noun", "Bài 06", "ນົມສົດ", "Sữa tươi"),
    ("ເບຍ", "Bia", "Beer", "bia", "noun", "Bài 06", "ເບຍລາວ", "Bia Lào (Beerlao)"),
    ("ເຫຼົ້າ", "Rượu", "Liquor / Alcohol", "lao", "noun", "Bài 06", "ເຫຼົ້າຂາວ", "Rượu trắng"),
    ("ແຊບ", "Ngon", "Delicious / Tasty", "saep", "adjective", "Bài 06", "ອາຫານແຊບຫຼາຍ", "Đồ ăn rất ngon"),
    ("ເຜັດ", "Cay", "Spicy / Hot", "phet", "adjective", "Bài 06", "ເຜັດຫຼາຍ", "Rất cay"),
    ("ບໍ່ເຜັດ", "Không cay", "Not spicy", "baw-phet", "phrase", "Bài 06", "ເອົາບໍ່ເຜັດ", "Lấy loại không cay"),
    ("ຫວານ", "Ngọt", "Sweet", "vaan", "adjective", "Bài 06", "ຫວານເກີນໄປ", "Ngọt quá"),
    ("ເຄັມ", "Mặn", "Salty", "khem", "adjective", "Bài 06", "ເຄັມຫຼາຍ", "Mặn quá"),
    ("ສົ້ມ", "Chua", "Sour", "som", "adjective", "Bài 06", "ໝາກນາວສົ້ມ", "Quả chanh chua"),
    ("ຂົມ", "Đắng", "Bitter", "khom", "adjective", "Bài 06", "ຢາຂົມ", "Thuốc đắng"),
    ("ຮ້ອນ", "Nóng", "Hot", "hawn", "adjective", "Bài 06", "ນ້ຳຮ້ອນ", "Nước nóng"),
    ("ເຢັນ", "Lạnh / Mát", "Cold / Cool", "yen", "adjective", "Bài 06", "ນ້ຳເຢັນ", "Nước lạnh"),
    ("ຫິວ", "Đói / Thèm", "Hungry", "hiv", "adjective", "Bài 06", "ຫິວເຂົ້າ", "Đói bụng"),
    ("ອີ່ມ", "No (no bụng)", "Full (after eating)", "eem", "adjective", "Bài 06", "ອີ່ມແລ້ວ", "No rồi"),

    # =========================================================================
    # BÀI 7: MUA SẮM & CHỢ BÚA (SHOPPING & MARKET) - 45 entries
    # =========================================================================
    ("ຕະຫຼາດ", "Chợ", "Market", "ta-laat", "noun", "Bài 07", "ໄປຕະຫຼາດເຊົ້າ", "Đi chợ sáng"),
    ("ຮ້ານ", "Cửa hàng / Tiệm", "Shop / Store", "haan", "noun", "Bài 07", "ຮ້ານອາຫານ", "Quán ăn"),
    ("ຮ້ານອາຫານ", "Nhà hàng / Quán ăn", "Restaurant", "haan-aa-haan", "noun", "Bài 07", "ກິນເຂົ້າຢູ່ຮ້ານ", "Ăn ở quán"),
    ("ຮ້ານຄ້າ", "Cửa hàng bách hóa", "Grocery store", "haan-khaa", "noun", "Bài 07", "ຊື້ເຄື່ອງຢູ່ຮ້ານຄ້າ", "Mua đồ ở tiệm"),
    ("ຊື້", "Mua", "To buy", "seu", "verb", "Bài 07", "ຊື້ຫຍັງ", "Mua cái gì"),
    ("ຂາຍ", "Bán", "To sell", "khaai", "verb", "Bài 07", "ຂາຍດີ", "Bán đắt hàng"),
    ("ລາຄາ", "Giá cả / Mức giá", "Price / Cost", "laa-khaa", "noun", "Bài 07", "ລາຄາເທົ່າໃດ", "Giá bao nhiêu"),
    ("ເງິນ", "Tiền / Bạc", "Money / Silver", "ngoen", "noun", "Bài 07", "ຈ່າຍເງິນ", "Trả tiền"),
    ("ກີບ", "Đồng Kíp (tiền tệ Lào)", "Kip (Lao currency)", "keep", "noun", "Bài 07", "ສິບພັນກີບ", "Mười nghìn kíp"),
    ("ດົ່ງ", "Đồng (tiền Việt Nam)", "Dong (VND)", "dong", "noun", "Bài 07", "ເງິນດົ່ງ", "Tiền đồng"),
    ("ໂດລາ", "Đô la", "Dollar", "doh-laa", "noun", "Bài 07", "ໜຶ່ງຮ້ອຍໂດລາ", "Một trăm đô la"),
    ("ບາດ", "Đồng Bạt (Thái Lan)", "Baht (THB)", "baat", "noun", "Bài 07", "ຈ່າຍເປັນບາດ", "Trả bằng bạt"),
    ("ແພງ", "Đắt / Đắt đỏ", "Expensive", "phaeng", "adjective", "Bài 07", "ແພງຫຼາຍ", "Đắt quá"),
    ("ຖືກ", "Rẻ / Đúng", "Cheap / Correct", "theuk", "adjective", "Bài 07", "ລາຄາຖືກ", "Giá rẻ"),
    ("ຫຼຸດ", "Giảm / Bớt", "To discount / To reduce", "lut", "verb", "Bài 07", "ຫຼຸດໄດ້ບໍ", "Bớt được không"),
    ("ຫຼຸດລາຄາ", "Giảm giá", "Discount", "lut-laa-khaa", "phrase", "Bài 07", "ກະລຸນາຫຼຸດລາຄາ", "Xin hãy giảm giá"),
    ("ຈ່າຍ", "Trả / Thanh toán", "To pay", "chaai", "verb", "Bài 07", "ຈ່າຍເງິນສົດ", "Trả tiền mặt"),
    ("ເງິນສົດ", "Tiền mặt", "Cash", "ngoen-sot", "noun", "Bài 07", "ຮັບເງິນສົດ", "Nhận tiền mặt"),
    ("ເງິນທອນ", "Tiền thừa / Tiền thối", "Change (money)", "ngoen-thawn", "noun", "Bài 07", "ບໍ່ມີເງິນທອນ", "Không có tiền lẻ thối"),
    ("ໂອນເງິນ", "Chuyển khoản", "Bank transfer", "oon-ngoen", "verb", "Bài 07", "ໂອນເງິນໄດ້ບໍ", "Chuyển khoản được không"),
    ("ເຄື່ອງ", "Đồ đạc / Hàng hóa", "Thing / Goods", "khuang", "noun", "Bài 07", "ຊື້ເຄື່ອງ", "Mua sắm đồ"),
    ("ເສື້ອ", "Cái áo", "Shirt / Top", "seua", "noun", "Bài 07", "ເສື້ອເຊີດ", "Áo sơ mi"),
    ("ສິ້ນ", "Váy sinh (trang phục Lào)", "Lao traditional skirt (Sinh)", "seen", "noun", "Bài 07", "ນຸ່ງສິ້ນ", "Mặc váy sinh"),
    ("ໂສ້ງ", "Cái quần", "Trousers / Pants", "soong", "noun", "Bài 07", "ໂສ້ງຢີນ", "Quần jean"),
    ("ເກີບ", "Đôi giày / Dép", "Shoes", "koep", "noun", "Bài 07", "ເກີບຜ້າ", "Giày vải"),
    ("ຖົງຕີນ", "Đôi tất / Đôi vớ", "Socks", "thong-teen", "noun", "Bài 07", "ຖົງຕີນດຳ", "Tất đen"),
    ("ໝວກ", "Cái mũ / Nón", "Hat / Cap", "muak", "noun", "Bài 07", "ໃສ່ໝວກ", "Đội mũ"),
    ("ໂມງມື", "Đồng hồ đeo tay", "Wristwatch", "moong-meu", "noun", "Bài 07", "ໂມງມືງາມ", "Đồng hồ đẹp"),
    ("ແວ່ນຕາ", "Kính mắt", "Glasses", "vaen-taa", "noun", "Bài 07", "ແວ່ນຕາກັນແດດ", "Kính râm"),
    ("ສາຍແອວ", "Thắt lưng / Dây nịt", "Belt", "saai-aew", "noun", "Bài 07", "ສາຍແອວໜັງ", "Thắt lưng da"),
    ("ສີ", "Màu sắc", "Color", "see", "noun", "Bài 07", "ມັກສີຫຍັງ", "Thích màu gì"),
    ("ຂະໜາດ", "Kích cỡ / Size", "Size", "kha-naat", "noun", "Bài 07", "ຂະໜາດໃຫຍ່", "Cỡ lớn"),
    ("ໃຫຍ່", "Lớn / To", "Big / Large", "nyai", "adjective", "Bài 07", "ເຮືອນໃຫຍ່", "Nhà to"),
    ("ນ້ອຍ", "Nhỏ / Bé", "Small / Little", "noy", "adjective", "Bài 07", "ລົດນ້ອຍ", "Xe nhỏ"),
    ("ກິໂລ", "Kilôgam / Ký", "Kilogram (kg)", "ki-loh", "noun", "Bài 07", "ໜຶ່ງກິໂລ", "Một cân"),
    ("ລິດ", "Lít", "Liter", "lit", "noun", "Bài 07", "ນ້ຳໜຶ່ງລິດ", "Một lít nước"),
    ("ແມັດ", "Mét", "Meter", "maet", "noun", "Bài 07", "ຜ້າສອງແມັດ", "Hai mét vải"),
    ("ລອງ", "Thử", "To try", "lawng", "verb", "Bài 07", "ລອງນຸ່ງເບິ່ງ", "Mặc thử xem"),
    ("ເອົາ", "Lấy / Chọn", "To take / Want", "ao", "verb", "Bài 07", "ເອົາອັນນີ້", "Lấy cái này"),
    ("ບໍ່ເອົາ", "Không lấy", "Don't want", "baw-ao", "phrase", "Bài 07", "ຂ້ອຍບໍ່ເອົາ", "Tôi không lấy"),
    ("ມີອີກບໍ", "Còn nữa không?", "Do you have more?", "mee-eek-baw", "phrase", "Bài 07", "ມີສີອື່ນບໍ", "Có màu khác không"),
    ("ໃສ່ຖົງ", "Bỏ vào túi", "Put in a bag", "sai-thong", "phrase", "Bài 07", "ໃສ່ຖົງໃຫ້ແດ່", "Bỏ túi hộ tôi"),
    ("ຖົງຢາງ", "Túi nilon", "Plastic bag", "thong-yaang", "noun", "Bài 07", "ບໍ່ເອົາຖົງຢາງ", "Không lấy túi nilon"),
    ("ໃບຮັບເງິນ", "Hóa đơn / Biên lai", "Receipt", "bai-hap-ngoen", "noun", "Bài 07", "ຂໍໃບຮັບເງິນ", "Xin hóa đơn"),
    ("ລູກຄ້າ", "Khách hàng", "Customer", "luuk-khaa", "noun", "Bài 07", "ລູກຄ້າມາຫຼາຍ", "Khách đến đông"),

    # =========================================================================
    # BÀI 8: GIAO THÔNG & ĐI LẠI (TRANSPORTATION & DIRECTIONS) - 45 entries
    # =========================================================================
    ("ໄປ", "Đi", "To go", "pai", "verb", "Bài 08", "ໄປໃສ", "Đi đâu"),
    ("ມາ", "Đến / Về", "To come", "maa", "verb", "Bài 08", "ມາແຕ່ໃສ", "Đến từ đâu"),
    ("ຮອດ", "Tới / Đến nơi", "To arrive / To reach", "hawt", "verb", "Bài 08", "ຮອດແລ້ວ", "Đến nơi rồi"),
    ("ກັບ", "Trở về / Cùng với", "To return / With", "kap", "verb", "Bài 08", "ກັບບ້ານ", "Về nhà"),
    ("ທາງ", "Đường đi / Hướng", "Road / Way / Direction", "thaang", "noun", "Bài 08", "ຖາມທາງ", "Hỏi đường"),
    ("ຖະໜົນ", "Đường phố", "Street / Avenue", "tha-non", "noun", "Bài 08", "ຖະໜົນໃຫຍ່", "Đường lớn"),
    ("ລົດ", "Xe / Xe cộ", "Car / Vehicle", "lot", "noun", "Bài 08", "ຂີ່ລົດ", "Đi xe"),
    ("ລົດຈັກ", "Xe máy", "Motorbike", "lot-chak", "noun", "Bài 08", "ຂີ່ລົດຈັກ", "Đi xe máy"),
    ("ລົດຖີບ", "Xe đạp", "Bicycle", "lot-theep", "noun", "Bài 08", "ຂີ່ລົດຖີບ", "Đạp xe đạp"),
    ("ລົດໃຫຍ່", "Xe ô tô", "Car / Automobile", "lot-nyai", "noun", "Bài 08", "ຂັບລົດໃຫຍ່", "Lái xe hơi"),
    ("ລົດເມ", "Xe buýt", "Bus", "lot-meh", "noun", "Bài 08", "ຂຶ້ນລົດເມ", "Lên xe buýt"),
    ("ລົດຕຸກຕຸກ", "Xe Túc Túc", "Tuk-tuk", "lot-tuk-tuk", "noun", "Bài 08", "ຂີ່ລົດຕຸກຕຸກ", "Đi xe túc túc"),
    ("ລົດໄຟ", "Tàu hỏa", "Train", "lot-fai", "noun", "Bài 08", "ສະຖານີລົດໄຟ", "Ga tàu hỏa"),
    ("ຍົນ", "Máy bay", "Airplane", "nyon", "noun", "Bài 08", "ຂີ່ຍົນ", "Đi máy bay"),
    ("ເຮືອ", "Thuyền / Tàu thủy", "Boat / Ship", "heua", "noun", "Bài 08", "ຂີ່ເຮືອຂ້າມຂອງ", "Đi thuyền qua sông"),
    ("ສະໜາມບິນ", "Sân bay", "Airport", "sa-naam-bin", "noun", "Bài 08", "ສະໜາມບິນວັດໄຕ", "Sân bay Wattay"),
    ("ສະຖານີ", "Nhà ga / Trạm", "Station", "sa-thaa-nee", "noun", "Bài 08", "ສະຖານີລົດເມ", "Bến xe buýt"),
    ("ຂີ່", "Cưỡi / Đi (xe)", "To ride / To take (vehicle)", "khee", "verb", "Bài 08", "ຂີ່ລົດເມ", "Đi xe buýt"),
    ("ຂັບ", "Lái (xe)", "To drive", "khap", "verb", "Bài 08", "ຂັບລົດ", "Lái ô tô"),
    ("ຍ່າງ", "Đi bộ", "To walk", "nyaang", "verb", "Bài 08", "ຍ່າງໄປ", "Đi bộ sang"),
    ("ຢຸດ", "Dừng lại", "To stop", "yut", "verb", "Bài 08", "ຢຸດລົດ", "Dừng xe"),
    ("ຈອດ", "Đỗ xe / Tấp vào lề", "To park", "chawt", "verb", "Bài 08", "ຈອດຢູ່ນີ້", "Đỗ ở đây"),
    ("ລ້ຽວ", "Rẽ / Quẹo", "To turn", "liao", "verb", "Bài 08", "ລ້ຽວຊ້າຍ", "Rẽ trái"),
    ("ລ້ຽວຊ້າຍ", "Rẽ trái", "Turn left", "liao-saai", "phrase", "Bài 08", "ລ້ຽວຊ້າຍແລ້ວຊື່ໄປ", "Rẽ trái rồi đi thẳng"),
    ("ລ້ຽວຂວາ", "Rẽ phải", "Turn right", "liao-khwaa", "phrase", "Bài 08", "ລ້ຽວຂວາຢູ່ໄຟແດງ", "Rẽ phải ở đèn đỏ"),
    ("ຊື່ໄປ", "Đi thẳng", "Go straight", "seu-pai", "phrase", "Bài 08", "ຍ່າງຊື່ໄປເລີຍ", "Đi thẳng luôn"),
    ("ຊ້າຍ", "Bên trái", "Left", "saai", "noun", "Bài 08", "ຢູ່ເບື້ອງຊ້າຍ", "Ở phía bên trái"),
    ("ຂວາ", "Bên phải", "Right", "khwaa", "noun", "Bài 08", "ຢູ່ເບື້ອງຂວາ", "Ở phía bên phải"),
    ("ໜ້າ", "Phía trước / Mặt", "Front / Face", "naa", "noun", "Bài 08", "ຢູ່ຕໍ່ໜ້າ", "Ở phía trước"),
    ("ຫຼັງ", "Phía sau / Lưng", "Behind / Back", "lang", "noun", "Bài 08", "ຢູ່ທາງຫຼັງ", "Ở đằng sau"),
    ("ຂ້າງ", "Bên cạnh", "Beside / Next to", "khaang", "noun", "Bài 08", "ຢູ່ຂ້າງໂຮງຮຽນ", "Bên cạnh trường học"),
    ("ໃກ້", "Gần", "Near / Close", "klai", "adjective", "Bài 08", "ຢູ່ໃກ້ນີ້", "Ở gần đây"),
    ("ໄກ", "Xa", "Far", "kai", "adjective", "Bài 08", "ໄກຫຼາຍ", "Rất xa"),
    ("ໄຟແດງ", "Đèn giao thông / Đèn đỏ", "Traffic light / Red light", "fai-daeng", "noun", "Bài 08", "ໄຟຂຽວໄຟແດງ", "Đèn xanh đèn đỏ"),
    ("ຂົວ", "Cây cầu", "Bridge", "khua", "noun", "Bài 08", "ຂົວມິດຕະພາບ", "Cầu Hữu Nghị"),
    ("ສີ່ແຍກ", "Ngã tư", "Intersection / Crossroads", "see-nyaek", "noun", "Bài 08", "ຮອດສີ່ແຍກ", "Đến ngã tư"),
    ("ສາມແຍກ", "Ngã ba", "Three-way junction", "saam-nyaek", "noun", "Bài 08", "ສາມແຍກໄຟແດງ", "Ngã ba đèn đỏ"),
    ("ປີ້", "Vé (xe, tàu)", "Ticket", "pee", "noun", "Bài 08", "ຊື້ປີ້ລົດ", "Mua vé xe"),
    ("ນ້ຳມັນ", "Xăng dầu", "Gasoline / Fuel", "nam-man", "noun", "Bài 08", "ປ້ຳນ້ຳມັນ", "Cây xăng"),
    ("ປ້ຳນ້ຳມັນ", "Trạm xăng", "Gas station", "pam-nam-man", "noun", "Bài 08", "ເຕີມນ້ຳມັນ", "Đổ xăng"),
    ("ຫຼົງທາງ", "Lạc đường", "Lost / Lost way", "long-thaang", "verb", "Bài 08", "ຂ້ອຍຫຼົງທາງແລ້ວ", "Tôi lạc đường rồi"),
    ("ແຜນທີ່", "Bản đồ", "Map", "phaen-thee", "noun", "Bài 08", "ເບິ່ງແຜນທີ່", "Xem bản đồ"),
    ("ປອດໄພ", "An toàn", "Safe", "pawt-phai", "adjective", "Bài 08", "ເດີນທາງປອດໄພ", "Đi đường bình an"),
    ("ອຸບັດຕິເຫດ", "Tai nạn", "Accident", "u-bat-ti-het", "noun", "Bài 08", "ເກີດອຸບັດຕິເຫດ", "Xảy ra tai nạn"),
    ("ໄວ", "Nhanh chóng", "Speedy", "vai", "adverb", "Bài 08", "ຢ່າຂັບໄວ", "Đừng phóng nhanh"),

    # =========================================================================
    # BÀI 9: NGHỀ NGHIỆP & NƠI CHỐN (PROFESSIONS & PLACES) - 45 entries
    # =========================================================================
    ("ວຽກ", "Công việc", "Job / Work", "viak", "noun", "Bài 09", "ເຮັດວຽກຫຍັງ", "Làm công việc gì"),
    ("ເຮັດວຽກ", "Làm việc", "To work", "het-viak", "verb", "Bài 09", "ເຮັດວຽກຢູ່ໃສ", "Làm việc ở đâu"),
    ("ອາຊີບ", "Nghề nghiệp", "Profession / Occupation", "aa-xeep", "noun", "Bài 09", "ອາຊີບຫຍັງ", "Làm nghề gì"),
    ("ທ່ານໝໍ", "Bác sĩ", "Doctor", "thaan-maw", "noun", "Bài 09", "ທ່ານໝໍປິ່ນປົວ", "Bác sĩ chữa bệnh"),
    ("ໝໍປິ່ນປົວ", "Bác sĩ điều trị", "Medical doctor", "maw-pin-pua", "noun", "Bài 09", "ໄປຫາໝໍ", "Đi khám bác sĩ"),
    ("ພະຍາບານ", "Y tá / Điều dưỡng", "Nurse", "pha-nyaa-baan", "noun", "Bài 09", "ພະຍາບານດູແລ", "Y tá chăm sóc"),
    ("ຕຳຫຼວດ", "Cảnh sát / Công an", "Police", "tam-luat", "noun", "Bài 09", "ຕຳຫຼວດຈະລາຈອນ", "Cảnh sát giao thông"),
    ("ທະຫານ", "Bộ đội / Quân nhân", "Soldier / Military", "tha-haan", "noun", "Bài 09", "ທະຫານປ້ອງກັນຊາດ", "Bộ đội bảo vệ tổ quốc"),
    ("ພະນັກງານ", "Nhân viên / Cán bộ", "Employee / Staff", "pha-nak-ngaan", "noun", "Bài 09", "ພະນັກງານບໍລິສັດ", "Nhân viên công ty"),
    ("ຊາວນາ", "Nông dân", "Farmer", "xaao-naa", "noun", "Bài 09", "ຊາວນາເຮັດນາ", "Nông dân làm ruộng"),
    ("ແມ່ຄ້າ", "Người bán hàng / Tiểu thương", "Vendor / Merchant", "mae-khaa", "noun", "Bài 09", "ແມ່ຄ້າໃຈດີ", "Bà bán hàng vui vẻ"),
    ("ນັກທຸລະກິດ", "Doanh nhân", "Businessman", "nak-thu-la-kit", "noun", "Bài 09", "ນັກທຸລະກິດເກັ່ງ", "Doanh nhân giỏi"),
    ("ວິສະວະກອນ", "Kỹ sư", "Engineer", "vi-sa-wa-kawn", "noun", "Bài 09", "ວິສະວະກອນໄຟຟ້າ", "Kỹ sư điện"),
    ("ຊ່າງໄມ້", "Thợ mộc", "Carpenter", "xaang-mai", "noun", "Bài 09", "ຊ່າງໄມ້ສີມືດີ", "Thợ mộc tay nghề cao"),
    ("ຊ່າງແປງ", "Thợ sửa chữa", "Mechanic / Repairman", "xaang-paeng", "noun", "Bài 09", "ຊ່າງແປງລົດ", "Thợ sửa xe"),
    ("ຄົນຂັບລົດ", "Tài xế / Lái xe", "Driver", "khon-khap-lot", "noun", "Bài 09", "ຄົນຂັບລົດໃຈດີ", "Bác tài xế hiền lành"),
    ("ແມ່ບ້ານ", "Người nội trợ", "Housewife / Housekeeper", "mae-baan", "noun", "Bài 09", "ແມ່ບ້ານເຮັດວຽກເຮືອນ", "Nội trợ làm việc nhà"),
    ("ໂຮງໝໍ", "Bệnh viện", "Hospital", "hong-maw", "noun", "Bài 09", "ໄປໂຮງໝໍ", "Đi bệnh viện"),
    ("ຮ້ານຂາຍຢາ", "Hiệu thuốc tây", "Pharmacy", "haan-khaai-yaa", "noun", "Bài 09", "ຊື້ຢາຢູ່ຮ້ານ", "Mua thuốc ở tiệm"),
    ("ຫ້ອງການ", "Văn phòng / Cơ quan", "Office", "hong-kaan", "noun", "Bài 09", "ຫ້ອງການເປີດແລ້ວ", "Văn phòng đã mở cửa"),
    ("ບໍລິສັດ", "Công ty", "Company", "baw-li-sat", "noun", "Bài 09", "ບໍລິສັດໃຫຍ່", "Công ty lớn"),
    ("ທະນາຄານ", "Ngân hàng", "Bank", "tha-naa-khaan", "noun", "Bài 09", "ຝາກເງິນຢູ່ທະນາຄານ", "Gửi tiền ở ngân hàng"),
    ("ໄປສະນີ", "Bưu điện", "Post office", "pai-sa-nee", "noun", "Bài 09", "ສົ່ງຈົດໝາຍ", "Gửi thư tại bưu điện"),
    ("ວັດ", "Chùa / Ngôi chùa", "Buddhist temple / Wat", "vat", "noun", "Bài 09", "ໄປວັດໄຫວ້ພຣະ", "Đi chùa lễ Phật"),
    ("ພຣະ", "Sư thầy / Nhà sư", "Monk / Buddha", "phra", "noun", "Bài 09", "ໃສ່ບາດພຣະ", "Cúng dường chư tăng"),
    ("ສະຖານທູດ", "Đại sứ quán", "Embassy", "sa-thaan-thuut", "noun", "Bài 09", "ສະຖານທູດຫວຽດນາມ", "Đại sứ quán Việt Nam"),
    ("ໂຮງແຮມ", "Khách sạn", "Hotel", "hong-haem", "noun", "Bài 09", "ພັກຢູ່ໂຮງແຮມ", "Nghỉ tại khách sạn"),
    ("ຫ້ອງນ້ຳ", "Nhà vệ sinh", "Toilet / Restroom", "hong-nam", "noun", "Bài 09", "ຫ້ອງນ້ຳຢູ່ໃສ", "Nhà vệ sinh ở đâu"),
    ("ສວນສາທາລະນະ", "Công viên công cộng", "Public park", "suan-saa-thaa-la-na", "noun", "Bài 09", "ຍ່າງຫຼິ້ນຢູ່ສວນ", "Dạo mát ở công viên"),
    ("ສະໜາມກິລາ", "Sân vận động", "Stadium / Sports field", "sa-naam-ki-laa", "noun", "Bài 09", "ເຕະບານຢູ່ສະໜາມ", "Đá bóng ở sân vận động"),
    ("ເມືອງ", "Thị xã / Huyện / Đô thị", "Town / District / City", "muang", "noun", "Bài 09", "ເມືອງຫຼວງ", "Thủ đô"),
    ("ແຂວງ", "Tỉnh", "Province", "khwaeng", "noun", "Bài 09", "ແຂວງຈຳປາສັກ", "Tỉnh Champasak"),
    ("ນະຄອນຫຼວງ", "Thủ đô / Thành phố lớn", "Capital city", "na-khon-luang", "noun", "Bài 09", "ນະຄອນຫຼວງວຽງຈັນ", "Thủ đô Vientiane"),
    ("ວຽງຈັນ", "Viêng Chăn (Vientiane)", "Vientiane", "viang-chan", "noun", "Bài 09", "ຢູ່ນະຄອນຫຼວງວຽງຈັນ", "Ở Viêng Chăn"),
    ("ຫຼວງພະບາງ", "Luông Pha Băng", "Luang Prabang", "luang-pha-baang", "noun", "Bài 09", "ເມືອງມໍລະດົກໂລກ", "Thành phố di sản thế giới"),
    ("ປາກເຊ", "Paksé", "Pakse", "paak-seh", "noun", "Bài 09", "ເມືອງປາກເຊ", "Thành phố Paksé"),
    ("ສະຫວັນນະເຂດ", "Savannakhet", "Savannakhet", "sa-van-na-khet", "noun", "Bài 09", "ແຂວງສະຫວັນນະເຂດ", "Tỉnh Savannakhet"),
    ("ແມ່ນ້ຳຂອງ", "Sông Mê Kông", "Mekong River", "mae-nam-khawng", "noun", "Bài 09", "ແຄມແມ່ນ້ຳຂອງ", "Bờ sông Mê Kông"),
    ("ພູ", "Ngọn núi", "Mountain", "phuu", "noun", "Bài 09", "ພູສູງ", "Núi cao"),
    ("ປ່າໄມ້", "Rừng cây", "Forest", "paa-mai", "noun", "Bài 09", "ປ່າໄມ້ຂຽວສົດ", "Rừng xanh mướt"),
    ("ນ້ຳຕົກຕາດ", "Thác nước", "Waterfall", "nam-tok-taat", "noun", "Bài 09", "ຕາດກວາງຊີ", "Thác Kuang Si"),
    ("ຖ້ຳ", "Hang động", "Cave", "tham", "noun", "Bài 09", "ຖ້ຳກອງລໍ", "Hang Kong Lor"),
    ("ທ່ອງທ່ຽວ", "Du lịch", "Travel / Tourism", "thawng-thiaw", "verb", "Bài 09", "ໄປທ່ອງທ່ຽວ", "Đi du lịch"),
    ("ສະຖານທີ່", "Địa điểm / Thắng cảnh", "Place / Location", "sa-thaan-thee", "noun", "Bài 09", "ສະຖານທີ່ທ່ອງທ່ຽວ", "Điểm du lịch"),
    ("ປະຕູໄຊ", "Khải Hoàn Môn Patuxay", "Patuxay Monument", "pa-tuu-xai", "noun", "Bài 09", "ທ່ຽວຊົມປະຕູໄຊ", "Tham quan Patuxay"),

    # =========================================================================
    # BÀI 10: NHÀ CỬA & SINH HOẠT HẰNG NGÀY (HOME & DAILY ROUTINES) - 45 entries
    # =========================================================================
    ("ຕື່ນນອນ", "Thức dậy", "To wake up", "teun-nawn", "verb", "Bài 10", "ຕື່ນນອນແຕ່ເຊົ້າ", "Thức dậy từ sớm"),
    ("ນອນ", "Ngủ", "To sleep", "nawn", "verb", "Bài 10", "ເຂົ້ານອນໄວ", "Đi ngủ sớm"),
    ("ຫຼັບ", "Ngủ say", "Asleep", "lap", "verb", "Bài 10", "ນອນຫຼັບດີ", "Ngủ ngon giấc"),
    ("ອາບນ້ຳ", "Tắm rửa", "To take a shower / bath", "aap-nam", "verb", "Bài 10", "ອາບນ້ຳຕອນແລງ", "Tắm buổi chiều"),
    ("ຖູແຂ້ວ", "Đánh răng", "To brush teeth", "thuu-khaew", "verb", "Bài 10", "ຖູແຂ້ວທຸກມື້", "Đánh răng mỗi ngày"),
    ("ລ້າງໜ້າ", "Rửa mặt", "To wash face", "laang-naa", "verb", "Bài 10", "ລ້າງໜ້າດ້ວຍນ້ຳເຢັນ", "Rửa mặt bằng nước mát"),
    ("ລ້າງມື", "Rửa tay", "To wash hands", "laang-meu", "verb", "Bài 10", "ລ້າງມືກ່ອນກິນເຂົ້າ", "Rửa tay trước khi ăn"),
    ("ນຸ່ງເຄື່ອງ", "Mặc quần áo", "To get dressed", "nung-khuang", "verb", "Bài 10", "ນຸ່ງເຄື່ອງງາມ", "Mặc đồ đẹp"),
    ("ຊັກເຄື່ອງ", "Giặt quần áo", "To do laundry", "xak-khuang", "verb", "Bài 10", "ຊັກເຄື່ອງທ້າຍອາທິດ", "Giặt đồ cuối tuần"),
    ("ຮີດເຄື່ອງ", "Là / Ủi quần áo", "To iron clothes", "heet-khuang", "verb", "Bài 10", "ຮີດເສື້ອ", "Ủi áo"),
    ("ແຕ່ງກິນ", "Nấu ăn", "To cook", "taeng-kin", "verb", "Bài 10", "ແມ່ແຕ່ງກິນແຊບ", "Mẹ nấu ăn ngon"),
    ("ເຮັດອາຫານ", "Nấu món ăn", "To prepare food", "het-aa-haan", "verb", "Bài 10", "ເຮັດອາຫານລາວ", "Nấu món ăn Lào"),
    ("ລ້າງຖ້ວຍ", "Rửa bát", "To wash dishes", "laang-thuay", "verb", "Bài 10", "ລ້າງຖ້ວຍຊ່ວຍແມ່", "Rửa bát giúp mẹ"),
    ("ກວາດເຮືອນ", "Quét nhà", "To sweep the house", "kwaat-heuan", "verb", "Bài 10", "ກວາດເຮືອນໃຫ້ສະອາດ", "Quét nhà sạch sẽ"),
    ("ຖູເຮືອນ", "Lau nhà", "To mop the floor", "thuu-heuan", "verb", "Bài 10", "ຖູເຮືອນທຸກມື້", "Lau nhà hằng ngày"),
    ("ເປີດ", "Mở", "To open / To turn on", "poet", "verb", "Bài 10", "ເປີດປະຕູ", "Mở cửa"),
    ("ອັດ", "Đóng / Khép", "To close / To shut", "at", "verb", "Bài 10", "ອັດປ່ອງຢ້ຽມ", "Đóng cửa sổ"),
    ("ປິດ", "Tắt / Đóng", "To turn off / To close", "pit", "verb", "Bài 10", "ປິດໄຟ", "Tắt đèn"),
    ("ປະຕູ", "Cửa chính / Cổng", "Door / Gate", "pa-tuu", "noun", "Bài 10", "ປະຕູໃຫຍ່", "Cửa lớn"),
    ("ປ່ອງຢ້ຽມ", "Cửa sổ", "Window", "pawng-yiam", "noun", "Bài 10", "ເປີດປ່ອງຢ້ຽມ", "Mở cửa sổ"),
    ("ຫ້ອງນອນ", "Phòng ngủ", "Bedroom", "hong-nawn", "noun", "Bài 10", "ຫ້ອງນອນກວ້າງ", "Phòng ngủ rộng"),
    ("ຫ້ອງຮັບແຂກ", "Phòng khách", "Living room", "hong-hap-khaek", "noun", "Bài 10", "ນັ່ງຫ້ອງຮັບແຂກ", "Ngồi phòng khách"),
    ("ຫ້ອງຄົວ", "Nhà bếp", "Kitchen", "hong-khua", "noun", "Bài 10", "ແຕ່ງກິນໃນຫ້ອງຄົວ", "Nấu nướng trong bếp"),
    ("ຕຽງ", "Cái giường", "Bed", "tiang", "noun", "Bài 10", "ຕຽງນອນ", "Giường ngủ"),
    ("ໝອນ", "Cái gối", "Pillow", "mawn", "noun", "Bài 10", "ໝອນນຸ່ມ", "Gối êm"),
    ("ຜ້າຫົ່ມ", "Cái chăn / Mền", "Blanket", "phaa-hom", "noun", "Bài 10", "ຫົ່ມຜ້າຫົ່ມ", "Đắp chăn"),
    ("ມຸ້ງ", "Cái màn / Mùng", "Mosquito net", "mung", "noun", "Bài 10", "ກາງມຸ້ງ", "Mắc màn"),
    ("ພັດລົມ", "Cái quạt máy", "Electric fan", "phat-lom", "noun", "Bài 10", "ເປີດພັດລົມ", "Bật quạt"),
    ("ແອເຢັນ", "Máy điều hòa", "Air conditioner", "ae-yen", "noun", "Bài 10", "ເປີດແອເຢັນ", "Bật điều hòa"),
    ("ຕູ້ເຢັນ", "Tủ lạnh", "Refrigerator", "tuu-yen", "noun", "Bài 10", "ເອົານ້ຳໃນຕູ້ເຢັນ", "Lấy nước trong tủ lạnh"),
    ("ຕູ້ເສື້ອຜ້າ", "Tủ quần áo", "Wardrobe", "tuu-seua-phaa", "noun", "Bài 10", "ຕູ້ໄມ້", "Tủ gỗ"),
    ("ໂທລະທັດ", "Ti vi", "Television", "tho-la-that", "noun", "Bài 10", "ເບິ່ງໂທລະທັດ", "Xem tivi"),
    ("ໂທລະສັບ", "Điện thoại", "Telephone / Mobile", "tho-la-sap", "noun", "Bài 10", "ໂທລະສັບມືຖື", "Điện thoại di động"),
    ("ຄອມພິວເຕີ", "Máy vi tính", "Computer", "khawm-phiw-toe", "noun", "Bài 10", "ຫຼິ້ນຄອມພິວເຕີ", "Dùng máy tính"),
    ("ອິນເຕີເນັດ", "Mạng Internet", "Internet", "in-toe-net", "noun", "Bài 10", "ຕໍ່ອິນເຕີເນັດ", "Kết nối internet"),
    ("ໄຟຟ້າ", "Điện lực / Đèn điện", "Electricity", "fai-faa", "noun", "Bài 10", "ໄຟຟ້າມອດ", "Mất điện"),
    ("ສະອາດ", "Sạch sẽ", "Clean", "sa-aat", "adjective", "Bài 10", "ເຮືອນສະອາດ", "Nhà cửa sạch sẽ"),
    ("ເປື້ອນ", "Bẩn / Dơ", "Dirty", "puan", "adjective", "Bài 10", "ເສື້ອເປື້ອນ", "Áo bẩn"),
    ("ກວ້າງ", "Rộng rãi", "Spacious / Wide", "kwaang", "adjective", "Bài 10", "ຫ້ອງກວ້າງ", "Phòng rộng"),
    ("ແຄບ", "Hẹp / Chật", "Narrow", "khaep", "adjective", "Bài 10", "ທາງແຄບ", "Đường hẹp"),
    ("ງຽບ", "Yên tĩnh", "Quiet", "ngiap", "adjective", "Bài 10", "ບ່ອນນີ້ງຽບດີ", "Nơi này yên tĩnh"),
    ("ດັງ", "Ồn ào / Vang to", "Noisy / Loud", "dang", "adjective", "Bài 10", "ສຽງດັງຫຼາຍ", "Tiếng to quá"),
    ("ໂທ", "Gọi điện", "To call (phone)", "thoh", "verb", "Bài 10", "ໂທຫາຂ້ອຍເດີ", "Gọi cho tôi nhé"),
    ("ສົ່ງ", "Gửi đi", "To send", "song", "verb", "Bài 10", "ສົ່ງຂໍ້ຄວາມ", "Gửi tin nhắn"),
    ("ຂໍ້ຄວາມ", "Tin nhắn", "Message", "khaw-khwaam", "noun", "Bài 10", "ໄດ້ຮັບຂໍ້ຄວາມ", "Nhận được tin nhắn"),

    # =========================================================================
    # BÀI 11: MÀU SẮC, TÍNH TỪ & MÔ TẢ (COLORS & ADJECTIVES) - 45 entries
    # =========================================================================
    ("ສີຂາວ", "Màu trắng", "White color", "see-khaao", "noun", "Bài 11", "ເສື້ອສີຂາວ", "Áo màu trắng"),
    ("ສີດຳ", "Màu đen", "Black color", "see-dam", "noun", "Bài 11", "ລົດສີດຳ", "Xe màu đen"),
    ("ສີແດງ", "Màu đỏ", "Red color", "see-daeng", "noun", "Bài 11", "ດອກໄມ້ສີແດງ", "Bông hoa màu đỏ"),
    ("ສີຂຽວ", "Màu xanh lá cây", "Green color", "see-khiao", "noun", "Bài 11", "ໃບໄມ້ສີຂຽວ", "Lá cây màu xanh"),
    ("ສີຟ້າ", "Màu xanh da trời", "Sky blue color", "see-faa", "noun", "Bài 11", "ທ້ອງຟ້າສີຟ້າ", "Bầu trời màu xanh"),
    ("ສີນ້ຳເງິນ", "Màu xanh nước biển đậm", "Navy / Dark blue", "see-nam-ngoen", "noun", "Bài 11", "ສີນ້ຳເງິນງາມ", "Màu xanh nước biển đẹp"),
    ("ສີເຫຼືອງ", "Màu vàng", "Yellow color", "see-leuang", "noun", "Bài 11", "ແສງຕາເວັນສີເຫຼືອງ", "Ánh mặt trời vàng"),
    ("ສີສົ້ມ", "Màu cam", "Orange color", "see-som", "noun", "Bài 11", "ໝາກກ້ຽງສີສົ້ມ", "Quả cam màu da cam"),
    ("ສີບົວ", "Màu hồng", "Pink color", "see-bua", "noun", "Bài 11", "ດອກບົວສີບົວ", "Hoa sen màu hồng"),
    ("ສີມ່ວງ", "Màu tím", "Purple / Violet", "see-muang", "noun", "Bài 11", "ດອກໄມ້ສີມ່ວງ", "Hoa màu tím"),
    ("ສີນ້ຳຕານ", "Màu nâu", "Brown color", "see-nam-taan", "noun", "Bài 11", "ໂຕະສີນ້ຳຕານ", "Bàn màu nâu"),
    ("ສີເທົາ", "Màu xám", "Grey color", "see-thao", "noun", "Bài 11", "ແມວສີເທົາ", "Con mèo xám"),
    ("ດີ", "Tốt / Đẹp", "Good", "dee", "adjective", "Bài 11", "ຄົນດີ", "Người tốt"),
    ("ບໍ່ດີ", "Không tốt / Xấu", "Bad / Not good", "baw-dee", "adjective", "Bài 11", "ອາກາດບໍ່ດີ", "Thời tiết không tốt"),
    ("ໃໝ່", "Mới", "New", "mai", "adjective", "Bài 11", "ລົດໃໝ່", "Xe mới"),
    ("ເກົ່າ", "Cũ", "Old (thing)", "kao", "adjective", "Bài 11", "ປຶ້ມເກົ່າ", "Quyển sách cũ"),
    ("ແກ່", "Già", "Old (person)", "kae", "adjective", "Bài 11", "ຄົນແກ່", "Người già"),
    ("ໜຸ່ມ", "Trẻ tuổi", "Young", "num", "adjective", "Bài 11", "ໄວໜຸ່ມ", "Giới trẻ"),
    ("ຍາວ", "Dài", "Long", "nyaao", "adjective", "Bài 11", "ໄມ້ຍາວ", "Cây gậy dài"),
    ("ສັ້ນ", "Ngắn", "Short (length)", "san", "adjective", "Bài 11", "ໂສ້ງສັ້ນ", "Quần soóc ngắn"),
    ("ໜາ", "Dày", "Thick", "naa", "adjective", "Bài 11", "ປຶ້ມໜາ", "Quyển sách dày"),
    ("ບາງ", "Mỏng", "Thin", "baang", "adjective", "Bài 11", "ເຈ້ຍບາງ", "Tờ giấy mỏng"),
    ("ໜັກ", "Nặng", "Heavy", "nak", "adjective", "Bài 11", "ກະເປົາໜັກ", "Cặp sách nặng"),
    ("ເບົາ", "Nhẹ", "Light (weight)", "bao", "adjective", "Bài 11", "ຂອງເບົາ", "Đồ nhẹ"),
    ("ແຂງ", "Cứng / Khỏe", "Hard / Strong", "khaeng", "adjective", "Bài 11", "ກ້ອນຫີນແຂງ", "Hòn đá cứng"),
    ("ອ່ອນ", "Mềm / Yếu", "Soft / Weak", "awn", "adjective", "Bài 11", "ໝອນອ່ອນ", "Gối mềm"),
    ("ແຈ້ງ", "Sáng sủa / Rõ ràng", "Bright / Clear", "chaeng", "adjective", "Bài 11", "ຕອນເຊົ້າແຈ້ງດີ", "Buổi sáng trời sáng tỏ"),
    ("ມືດ", "Tối tăm", "Dark", "muut", "adjective", "Bài 11", "ຫ້ອງມືດ", "Phòng tối"),
    ("ຮ້ອນ", "Nóng nực", "Hot (weather/food)", "hawn", "adjective", "Bài 11", "ມື້ນີ້ຮ້ອນຫຼາຍ", "Hôm nay trời rất nóng"),
    ("ໜາວ", "Lạnh giá", "Cold (weather)", "naao", "adjective", "Bài 11", "ລະດູໜາວ", "Mùa đông lạnh"),
    ("ອົບເອົ້າ", "Oi bức", "Humid / Muggy", "op-ao", "adjective", "Bài 11", "ອາກາດອົບເອົ້າ", "Không khí oi ả"),
    ("ແຫ້ງ", "Khô ráo", "Dry", "haeng", "adjective", "Bài 11", "ລະດູແລ້ງ", "Mùa khô"),
    ("ປຽກ", "Ướt át", "Wet", "piak", "adjective", "Bài 11", "ເສື້ອປຽກ", "Áo bị ướt"),
    ("ມ່ວນ", "Vui vẻ / Thú vị", "Fun / Enjoyable", "muan", "adjective", "Bài 11", "ໄປທ່ຽວມ່ວນຫຼາຍ", "Đi chơi rất vui"),
    ("ເສົ້າ", "Buồn rầu", "Sad", "sao", "adjective", "Bài 11", "ໜ້າເສົ້າ", "Mặt buồn"),
    ("ໂກດ", "Giận dữ / Tức giận", "Angry", "kot", "verb", "Bài 11", "ຢ່າໂກດເດີ", "Đừng giận nhé"),
    ("ຢ້ານ", "Sợ hãi", "Scared / Afraid", "yaan", "verb", "Bài 11", "ຢ້ານຄວາມມືດ", "Sợ bóng tối"),
    ("ກ້າຫານ", "Dũng cảm", "Brave", "kaa-haan", "adjective", "Bài 11", "ທະຫານກ້າຫານ", "Chiến sĩ dũng cảm"),
    ("ງາມ", "Xinh đẹp", "Pretty", "ngaam", "adjective", "Bài 11", "ສາວງາມ", "Cô gái đẹp"),
    ("ຂີ້ຮ້າຍ", "Xấu xí / Tệ", "Ugly / Bad", "khee-haai", "adjective", "Bài 11", "ຄົນຂີ້ຮ້າຍ", "Kẻ xấu tính"),
    ("ສະບາຍ", "Dễ chịu / Khỏe", "Comfortable", "sa-baai", "adjective", "Bài 11", "ຢູ່ສະບາຍ", "Sống thoải mái"),
    ("ເມື່ອຍ", "Mệt mỏi", "Tired", "meuay", "adjective", "Bài 11", "ເຮັດວຽກເມື່ອຍ", "Làm việc mệt"),
    ("ສຳຄັນ", "Quan trọng", "Important", "sam-khan", "adjective", "Bài 11", "ເລື່ອງສຳຄັນ", "Chuyện quan trọng"),
    ("ພິເສດ", "Đặc biệt", "Special", "phi-set", "adjective", "Bài 11", "ອາຫານພິເສດ", "Món ăn đặc biệt"),
    ("ທຳມະດາ", "Bình thường", "Normal / Ordinary", "tham-ma-daa", "adjective", "Bài 11", "ມື້ທຳມະດາ", "Ngày bình thường"),

    # =========================================================================
    # BÀI 12: ĐỘNG TỪ & GIAO TIẾP HÀNG NGÀY (COMMON VERBS & DIALOGUE) - 45 entries
    # =========================================================================
    ("ເຮັດ", "Làm", "To do / To make", "het", "verb", "Bài 12", "ເຮັດຫຍັງຢູ່", "Đang làm gì thế"),
    ("ເບິ່ງ", "Xem / Nhìn", "To look / To watch", "boeng", "verb", "Bài 12", "ເບິ່ງຮູບ", "Xem ảnh"),
    ("ເຫັນ", "Thấy / Trông thấy", "To see", "hen", "verb", "Bài 12", "ຂ້ອຍເຫັນແລ້ວ", "Tôi thấy rồi"),
    ("ຫາ", "Tìm / Kiếm", "To find / To seek", "haa", "verb", "Bài 12", "ຫາເງິນ", "Kiếm tiền"),
    ("ພົບ", "Gặp gỡ", "To meet", "phop", "verb", "Bài 12", "ພົບເພື່ອນ", "Gặp bạn bè"),
    ("ໃຫ້", "Cho / Tặng", "To give", "hai", "verb", "Bài 12", "ໃຫ້ເງິນ", "Cho tiền"),
    ("ເອົາ", "Lấy", "To take", "ao", "verb", "Bài 12", "ເອົາໃຫ້ຂ້ອຍ", "Đưa cho tôi"),
    ("ຮັບ", "Nhận", "To receive", "hap", "verb", "Bài 12", "ຮັບຂອງຂວັນ", "Nhận quà"),
    ("ສົ່ງ", "Gửi", "To send", "song", "verb", "Bài 12", "ສົ່ງຈົດໝາຍ", "Gửi thư"),
    ("ບອກ", "Bảo / Nói cho biết", "To tell", "bawk", "verb", "Bài 12", "ບອກຄວາມຈິງ", "Nói sự thật"),
    ("ລົມ", "Trò chuyện / Tán gẫu", "To chat", "lom", "verb", "Bài 12", "ລົມກັນ", "Nói chuyện với nhau"),
    ("ຫົວ", "Cười", "To laugh", "hua", "verb", "Bài 12", "ຫົວຂວັນ", "Cười vui vẻ"),
    ("ໄຫ້", "Khóc", "To cry", "hai", "verb", "Bài 12", "ຢ່າໄຫ້", "Đừng khóc"),
    ("ຫຼິ້ນ", "Chơi", "To play", "lin", "verb", "Bài 12", "ຫຼິ້ນກິລາ", "Chơi thể thao"),
    ("ເຕັ້ນ", "Nhảy múa / Khiêu vũ", "To dance / To jump", "ten", "verb", "Bài 12", "ເຕັ້ນລຳ", "Khiêu vũ"),
    ("ຮ້ອງເພງ", "Hát", "To sing", "hawng-pheng", "verb", "Bài 12", "ຮ້ອງເພງມ່ວນ", "Hát rất hay"),
    ("ຟ້ອນ", "Múa lăm-vông (điệu múa Lào)", "To dance traditional Lao dance", "fawn", "verb", "Bài 12", "ຟ້ອນລຳວົງ", "Múa Lăm-vông"),
    ("ຍ່າງ", "Bước đi", "To walk", "nyaang", "verb", "Bài 12", "ຍ່າງໄວ", "Đi nhanh"),
    ("ແລ່ນ", "Chạy", "To run", "laen", "verb", "Bài 12", "ແລ່ນອອກກຳລັງກາຍ", "Chạy tập thể dục"),
    ("ນັ່ງ", "Ngồi", "To sit", "nang", "verb", "Bài 12", "ນັ່ງລົງ", "Ngồi xuống"),
    ("ຢືນ", "Đứng", "To stand", "yeun", "verb", "Bài 12", "ຢືນຂຶ້ນ", "Đứng dậy"),
    ("ລໍຖ້າ", "Chờ đợi", "To wait", "law-thaa", "verb", "Bài 12", "ລໍຖ້າຈັກໜ້ອຍ", "Chờ một chút"),
    ("ເລີ່ມ", "Bắt đầu", "To start / To begin", "loem", "verb", "Bài 12", "ເລີ່ມຕົ້ນ", "Khởi đầu"),
    ("ແລ້ວ", "Xong / Rồi", "Finished / Already", "laew", "adverb", "Bài 12", "ເຮັດແລ້ວ", "Làm xong rồi"),
    ("ຍັງ", "Vẫn / Chưa", "Still / Yet", "nyang", "adverb", "Bài 12", "ຍັງບໍ່ແລ້ວ", "Vẫn chưa xong"),
    ("ຕ້ອງ", "Phải (cần phải)", "Must / Have to", "tawng", "verb", "Bài 12", "ຕ້ອງໄປດຽວນີ້", "Phải đi ngay bây giờ"),
    ("ຢາກ", "Muốn", "To want", "yaak", "verb", "Bài 12", "ຢາກກິນເຂົ້າ", "Muốn ăn cơm"),
    ("ມັກ", "Thích", "To like", "mak", "verb", "Bài 12", "ມັກພາສາລາວ", "Thích tiếng Lào"),
    ("ຊັງ", "Ghét", "To hate", "xang", "verb", "Bài 12", "ບໍ່ຊັງໃຜ", "Không ghét ai"),
    ("ເຊື່ອ", "Tin tưởng", "To believe", "xua", "verb", "Bài 12", "ຂ້ອຍເຊື່ອເຈົ້າ", "Tôi tin bạn"),
    ("ຫວັງ", "Hy vọng", "To hope", "vang", "verb", "Bài 12", "ຫວັງວ່າຈະດີ", "Hy vọng sẽ tốt"),
    ("ຊ່ວຍເຫຼືອ", "Cứu giúp / Tương trợ", "To assist", "xuay-leua", "verb", "Bài 12", "ຊ່ວຍເຫຼືອກັນ", "Tương trợ lẫn nhau"),
    ("ແບ່ງປັນ", "Chia sẻ", "To share", "baeng-pan", "verb", "Bài 12", "ແບ່ງປັນຄວາມຮູ້", "Chia sẻ kiến thức"),
    ("ຖ່າຍຮູບ", "Chụp ảnh", "To take a photo", "thaai-huup", "verb", "Bài 12", "ຖ່າຍຮູບງາມ", "Chụp ảnh đẹp"),
    ("ຮູບ", "Bức ảnh", "Picture / Image", "huup", "noun", "Bài 12", "ຮູບຖ່າຍ", "Tấm ảnh"),
    ("ຄິດຮອດ", "Nhớ (thương nhớ)", "To miss someone", "khit-hawt", "verb", "Bài 12", "ຄິດຮອດບ້ານ", "Nhớ nhà"),
    ("ດີໃຈ", "Vui mừng", "Glad / Happy", "dee-chai", "adjective", "Bài 12", "ດີໃຈຫຼາຍທີ່ໄດ້ພົບ", "Rất vui khi được gặp"),
    ("ເສຍໃຈ", "Buồn lòng / Lấy làm tiếc", "Sorry / Regretful", "sia-chai", "adjective", "Bài 12", "ຂ້ອຍເສຍໃຈນຳ", "Tôi xin chia buồn"),
    ("ໂຊກດີ", "May mắn", "Good luck", "xook-dee", "phrase", "Bài 12", "ຂໍໃຫ້ໂຊກດີ", "Chúc may mắn"),
    ("ສຳເລັດ", "Thành công", "Success / Completed", "sam-let", "adjective", "Bài 12", "ຂໍໃຫ້ສຳເລັດ", "Chúc thành công"),
    ("ແນ່ນອນ", "Chắc chắn", "Of course / Definitely", "naae-nawn", "adverb", "Bài 12", "ແນ່ນອນແລ້ວ", "Chắc chắn rồi"),
    ("ບາງເທື່ອ", "Có lẽ / Đôi khi", "Maybe / Sometimes", "baang-theua", "adverb", "Bài 12", "ບາງເທື່ອໄປ", "Đôi khi đi"),
    ("ແທ້", "Thật / Thật sự", "Really / Truly", "thae", "adverb", "Bài 12", "ແທ້ຫວາ", "Thật à?"),
    ("ແມ່ນແທ້", "Đúng thật", "Really true", "maen-thae", "phrase", "Bài 12", "ແມ່ນແທ້ໆ", "Đúng thật sự"),
    ("ສະບາຍໃຈ", "Thảnh thơi / An tâm", "At peace / Content", "sa-baai-chai", "adjective", "Bài 12", "ຮູ້ສຶກສະບາຍໃຈ", "Cảm thấy yên lòng"),
]


def build_dictionary():
    print(f"Tổng số từ trong database gốc: {len(VOCAB_DATABASE)}")
    
    # Chuẩn hóa toàn bộ từ vựng và loại bỏ trùng lặp
    unique_entries = {}
    for item in VOCAB_DATABASE:
        lao_word, vi, en, roman, pos, lesson, ex_lao, ex_vi = item
        norm_lao = normalize_lao(lao_word)
        norm_ex_lao = normalize_lao(ex_lao)
        
        # Nếu chưa có trong từ điển thì thêm vào
        if norm_lao not in unique_entries:
            unique_entries[norm_lao] = {
                "lao": norm_lao,
                "vi": vi.strip(),
                "en": en.strip(),
                "romanization": roman.strip(),
                "pos": pos.strip(),
                "lesson": lesson.strip(),
                "example_lao": norm_ex_lao,
                "example_vi": ex_vi.strip()
            }
            
    sorted_words = sorted(unique_entries.values(), key=lambda x: (x["lesson"], x["lao"]))
    
    os.makedirs(os.path.dirname(DICT_OUTPUT), exist_ok=True)
    with open(DICT_OUTPUT, mode="w", encoding="utf-8", newline="") as f:
        fieldnames = ["lao", "vi", "en", "romanization", "pos", "lesson", "example_lao", "example_vi"]
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(sorted_words)
        
    print(f"✅ Đã xuất từ điển giáo trình thành công ({len(sorted_words)} entries) -> {DICT_OUTPUT}")
    print(f"  • Cột dữ liệu: {fieldnames}")
    print(f"  • 100% từ vựng và câu ví dụ đã được chuẩn hóa Unicode NFC.")
    return len(sorted_words)


if __name__ == "__main__":
    build_dictionary()
